ember-learn/guides-source

guides/v1.10.0/pages.yml, guides/v1.11.0/pages.yml, guides/v1.12.0/pages.yml
https://github.com/ember-learn/guides-app/issues/4
=> fixing old pages.json

guides/v3.1.0/tutorial/service.md
Originally from https://github.com/emberjs/guides/pull/2326 
Thanks @martynling 🎉
=> Services: change to stubMapUtil and need to restart test server for unit tests

guides/v3.1.0/tutorial/simple-component.md
Originally from https://github.com/emberjs/guides/pull/2328
Thanks @ardenzhan 🎉
=> update 'final code' to be same as previous code

CONTRIBUTING.md, README.md
Part of preparing for the launch of the guides app. Feel free to add more commits on top of my work.
=> Add a README and copy over CONTRIBUTING.md from old guides

guides/v3.1.0/object-model/computed-properties-and-aggregate-data.md
ported from emberjs/guides#2325
cc @jal90
=> Updating off by 1 error, ported from emberjs/guides#2325

guides/v3.2.0/ember-inspector/component-tree.md, guides/v3.2.0/pages.yml
As the 3.2.0 version has already been cut we need to forward-port changes that are released into 3.1.0
This is just porting #45 👍
=> Forward porting #45

CONTRIBUTING.md, README.md
- Adds a blurb about forking repo for first time contributors
- Add link to github’s description of code fencing
=> readme.MD and contributing.MD review

guides/v3.0.0/testing/acceptance.md, guides/v3.1.0/testing/acceptance.md, guides/v3.2.0/testing/acceptance.md
=> Fix testing guides to link to ember test helpers.

guides/v3.3.0/applications/services.md, guides/v3.3.0/configuring-ember/debugging.md, guides/v3.3.0/contributing/adding-new-features.md, guides/v3.3.0/templates/conditionals.md, guides/v3.3.0/tutorial/service.md
Just spotted some small typos while reading through some of the 3.3.0 stuff.
=> small typos in 3.3

guides/v3.1.0/models/index.md
Just moved/removed a couple of characters around 🤓
=> Fixed minor typos in models/index.md

guides/v3.2.0/models/index.md, guides/v3.3.0/models/index.md
Propoaging PR #68 into later versions
=> include updates in #68 in later versions

guides/v2.18.0/tutorial/hbs-helper.md
For test: “it renders correctly for a Standalone rental” Lines to add (in green) should be: 
test(‘it renders correctly for a Standalone rental’, function(assert) { AND assert.equal(this.$().text().trim(), ‘Standalone’);
Lines to remove (in red) should be: 
assert.equal(this.$().text().trim(), ‘1234’);
Thank you for creating this guide
=> Minor issue with adding and removing lines of code

guides/v2.18.0/tutorial/hbs-helper.md, guides/v3.0.0/tutorial/hbs-helper.md
This is a continuation of https://github.com/ember-learn/guides-source/pull/70 and I have verified it locally 👍 
Can someone please review and merge
=> fixing tutorial diff and forward porting to 3.1.0

guides/v3.3.0/models/finding-records.md
Following up on #106 by applying same change for v3.3.0 docs
=> Differentiate when a promise/record is returned

guides/v3.3.0/tutorial/simple-component.md
As thoroughly described in #105 this is the only change left 😄
=> Add missing 'async' before function

guides/v3.2.0/templates/binding-element-attributes.md, guides/v3.3.0/templates/binding-element-attributes.md
See https://github.com/ember-learn/guides-source/pull/59
=> adding PR #59 into 3.2 and 3.3

guides/v3.2.0/tutorial/autocomplete-component.md
- It should be an async function.
- In the sample code right behind it, it is an async function.
=> function -> async function

MAINTAINERS.md
#113
Feel free to add anything directly to this PR.
=> add deployment instructions #113

guides/v3.0.0/tutorial/service.md, guides/v3.1.0/tutorial/service.md, guides/v3.2.0/tutorial/service.md, guides/v3.3.0/tutorial/service.md
This change matches super-rentals [source code](https://github.com/ember-learn/super-rentals/blob/master/app/utils/google-maps.js#L12)
=> remove unnecesary reference to window

guides/v3.3.0/testing/acceptance.md
These were all broken as they pointed to links that have since been removed
=> Fixed test helper links

MAINTAINERS.md
To clarify what is needed during release
=> Tweaking release instructions

guides/v3.4.0/index.md
Hey! This is my first open source pr. If I can change anything, let me know!
=> Updated learning team slack channel reference 

guides/v3.4.0/tutorial/acceptance-test.md, guides/v3.4.0/tutorial/autocomplete-component.md, guides/v3.4.0/tutorial/installing-addons.md, guides/v3.4.0/tutorial/model-hook.md, guides/v3.4.0/tutorial/routes-and-templates.md, guides/v3.4.0/tutorial/service.md
I got through the tutorial the other day and I found some mistakes in code diffs.
I fixed them. Could you take a look?
=> Fixed wrong diffs in Tutorial

guides/v3.4.0/templates/handlebars-basics.md
=> Added one sentence to say what a helper is #159

guides/v2.10.0/tutorial/routes-and-templates.md, guides/v2.11.0/tutorial/routes-and-templates.md, guides/v2.12.0/tutorial/routes-and-templates.md, guides/v2.13.0/tutorial/routes-and-templates.md, guides/v2.14.0/tutorial/routes-and-templates.md, guides/v2.15.0/tutorial/routes-and-templates.md, guides/v2.16.0/tutorial/routes-and-templates.md, guides/v2.17.0/tutorial/routes-and-templates.md, guides/v2.18.0/tutorial/routes-and-templates.md, guides/v2.3.0/tutorial/routes-and-templates.md, guides/v2.4.0/tutorial/routes-and-templates.md, guides/v2.5.0/tutorial/routes-and-templates.md, guides/v2.6.0/tutorial/routes-and-templates.md, guides/v2.7.0/tutorial/routes-and-templates.md, guides/v2.8.0/tutorial/routes-and-templates.md, guides/v2.9.0/tutorial/routes-and-templates.md, guides/v3.0.0/tutorial/routes-and-templates.md, guides/v3.1.0/tutorial/routes-and-templates.md, guides/v3.2.0/tutorial/routes-and-templates.md, guides/v3.3.0/tutorial/routes-and-templates.md, guides/v3.4.0/tutorial/routes-and-templates.md
A tutorial reader will notice more failing tests than what the documentation
specifies, due to some linter errors. Modify the provided content, to suppress
the linter errors.
=> routes-and-templates: Massage contact template content for linter.

guides/v3.4.0/controllers/index.md
Correcting a url from another PR, which I realized after merging should be relative. #163 #173
=> fix query params link to be relative #163

guides/v3.4.0/object-model/index.md
Fixes #155 
[rendered](https://github.com/ember-learn/guides-source/blob/e655e9abc7b3720e6964560c79eb8a5fcb29c01d/guides/v3.4.0/object-model/index.md)
=> docs(Objects in Ember): update intro to objects

guides/v3.4.0/routing/defining-your-routes.md
RE: #157
I was struggling a bit finding a good spot for this section to fit in, so I ended up settling with the bottom.  I didn't want to tamper with the existing section orders, because it felt like the content flowed really well. At any rate, let me know if I'm missing anything here or if I should dig more into the concepts!
=> Explain how to transition between Routes (#157)

guides/v3.4.0/tutorial/service.md, guides/v3.5.0/tutorial/service.md
Fixes https://github.com/ember-learn/guides-source/issues/195
Replaces this PR that I effed up trying to sync with the 3.5 files https://github.com/ember-learn/guides-source/pull/205
=> Replace jQuery in service.md code sample

guides/v3.5.0/tutorial/installing-addons.md
I was working through this tutorial today and found that my project would not build with this semicolon in place. Does that seem correct? Hope this is helpful if so.
=> Remove extra semicolon

guides/v3.5.0/components/defining-a-component.md
The text 'you to' was written twice
=> Update duplicate content

guides/v3.5.0/models/defining-models.md
Added to defining models page.
=> Added read-only attributes to defining models (#166)

guides/v3.5.0/routing/loading-and-error-substates.md
closes #35 
This is as much a sanity check of my understanding as it is an attempt to help the community :grin: 
Please let me know if I've missed anything.
=> Clarify loading search within a route (#35)

guides/v3.5.0/templates/writing-helpers.md
=> Update link to htmlSafe. 

guides/v3.5.0/pages.yml
I took the liberty to create a proposal of topics which should be advanced.
My method is mostly relying on my experience of using ember and which topics I used in a rather simple app. This is only the first stab. I have no hard opinion which should be advanced and which not. I hope I did understand correct where it should be added.
Issue link: https://github.com/ember-learn/guides-source/issues/191
=> Adding advanced flags to pages.yml

guides/v3.5.0/routing/defining-your-routes.md
Added examples for index routes as mentioned in issue link: 
https://github.com/ember-learn/guides-source/issues/156
=> Added examples for index routes

guides/v3.0.0/tutorial/routes-and-templates.md, guides/v3.1.0/tutorial/routes-and-templates.md, guides/v3.2.0/tutorial/routes-and-templates.md, guides/v3.3.0/tutorial/routes-and-templates.md, guides/v3.4.0/tutorial/routes-and-templates.md, guides/v3.5.0/tutorial/routes-and-templates.md
=> remove trailing slash typo

guides/v2.10.0/templates/links.md, guides/v2.11.0/templates/links.md, guides/v2.12.0/templates/links.md, guides/v2.13.0/templates/links.md, guides/v2.14.0/templates/links.md, guides/v2.15.0/templates/links.md, guides/v2.16.0/templates/links.md, guides/v2.17.0/templates/links.md, guides/v2.18.0/templates/links.md, guides/v2.3.0/templates/links.md, guides/v2.4.0/templates/links.md, guides/v2.5.0/templates/links.md, guides/v2.6.0/templates/links.md, guides/v2.7.0/templates/links.md, guides/v2.8.0/templates/links.md, guides/v2.9.0/templates/links.md, guides/v3.0.0/templates/links.md, guides/v3.1.0/templates/links.md, guides/v3.2.0/templates/links.md, guides/v3.3.0/templates/links.md, guides/v3.4.0/templates/links.md, guides/v3.5.0/templates/links.md, guides/v3.6.0/templates/links.md
https://github.com/ember-learn/guides-source/issues/310
=> Add link to the query parameters section in routing from links

guides/v3.6.0/addons-and-dependencies/managing-dependencies.md
My attempt at expanding the addons section, as per https://github.com/ember-learn/guides-source/issues/320.
This only covers the first of the two acceptance criteria on the ticket ("Expand the Addons section..."), as I don't have the expertise to address the second one.
=> Expand addons section

guides/v3.7.0/tutorial/autocomplete-component.md
`{{/list-filter}}` appears on line 21 in the sample code
=> Changed mention of list-filter from line 20 to 21

guides/v3.7.0/templates/input-helpers.md
Relates to https://github.com/ember-learn/guides-source/issues/181
=> Added clarity to event names on input helper (#181)

guides/v3.7.0/reference/syntax-conversion-guide.md
=> fix(syntax conversion guide): code samples tweaks

guides/v3.7.0/testing/acceptance.md
It contains references to the pauseTest() and resumeTest() wonderful and hidden functions.
=> Add Debugging Your Tests section to Acceptance

guides/v3.7.0/templates/built-in-helpers.md
As discussed in the Framework Core Team meeting
=> Add explicit link to all helpers in the API docs

guides/release/models/index.md
Basically that it's automatically available on routes.
Not sure if this is the best place for it. Was looking for like a blockquote example, but didn't find one, so maybe there is some syntax to make this stand out a bit.
=> models: add note about the store injection

guides/release/pages.yml
Reverts ember-learn/guides-source#419
=> Revert "Update pages.yml"

guides/release/tutorial/service.md
=> link to definition, phrase in active voice

guides/release/components/triggering-changes-with-actions.md
Resolves https://github.com/ember-learn/guides-source/issues/398
=> components(actions): start converting to class and @action decorator

guides/release/pages.yml, guides/release/reference/accessibility-guide.md
if merged, this adds an accessibility  sub-section to the references section of the guides.
=> added accessibility guide

guides/release/components/wrapping-content-in-a-component.md
Updates the description of how to use the block form to refer to angle brackets.
Any wording improvement suggestions are appreciated!
=> Update block form description for angle brackets

guides/release/getting-started/js-primer.md, guides/release/object-model/classes-and-instances.md, guides/release/object-model/reopening-classes-and-instances.md, guides/release/pages.yml
This reverts commit c8f68cbb6cf5528c2feb55e776e87128053bf8ed.
=> [Octane] Revert removal of sections

guides/release/pages.yml
Closes https://github.com/ember-learn/guides-source/issues/418.
Closes https://github.com/ember-learn/guides-source/issues/402.
What it says on the tin.
=> TOC | Re-order and re-title

guides/release/components/block-params.md
Part of https://github.com/ember-learn/guides-source/issues/395.
=> Update block params

guides/release/components/displaying-data.md
Closes https://github.com/ember-learn/guides-source/issues/397.
=> Update displaying data

guides/release/anatomy-of-an-app/index.md, guides/release/deploying/index.md, guides/release/pages.yml, guides/release/state-management/index.md, guides/release/upgrading/deprecations.md, guides/release/upgrading/editions.md, guides/release/upgrading/index.md
This PR creates some of the files missing from the Table of Contents so that we can start accepting PRs for the content.
=> Octane - Add placeholder files for the Table of Contents

guides/release/pages.yml, guides/release/state-management/computed-properties.md, guides/release/state-management/index.md, guides/release/state-management/patterns-for-state.md, guides/release/state-management/tracked-properties.md
Adds the State Management section. This section definitely will need polish in the future, I imagine more thorough discussions of state could be helpful (tried my best!). We also need to add a section on computed properties, @jenweber this would be great for anyone who has some time to volunteer since they're much more well understood.
Feedback definitely appreciated on the Patterns for State section (and all of it really!)
=> [OCTANE][FEAT] State Management

guides/release/templates/writing-helpers.md
Fixes #542 
1. Change format-currency helper
2. Change is-authenticated helper
=> [OCTANE] [CHORE] Writing helpers use class syntax #542

guides/release/templates/handlebars-basics.md
Itty bitty PR to fix one thing we overlooked.
=> Fix missing curly braces and file path

guides/release/models/handling-metadata.md, guides/release/models/pushing-records-into-the-store.md
I found these while working in #553. I fixed them there as well.
=> fix syntax errors in code examples for ember-data

guides/release/state-management/patterns-for-state.md, guides/release/upgrading/editions.md
@pzuraq apologies, the grammarian in me couldn't avoid changing this.
=> [OCTANE] nitpick: make run loop description consistent

guides/release/models/customizing-adapters.md
=> [OCTANE] use static class fields instead of init logic

guides/release/models/customizing-adapters.md
=> [OCTANE] rewrite text and example to use getters

config/environment.js
I am preparing this PR so that when the survey has ended we can remove the banner that prompts people to take it 👍
=> turning off the survey

config/environment.js, guides/release/pages.yml, package-lock.json, package.json
Fixes https://github.com/ember-learn/guides-source/issues/586
This is just implementing @jenweber's work by adding the required config. 
Here is a preview:
=> Preview banner

guides/release/state-management/index.md
This is had awkward wording and didn't make much sense. It seemed removing the offending sentence did not loose any meaning.
=> Remove awkward sentence

guides/release/components/arguments-and-attributes.md
=> #588 components/arguments-and-attributes

guides/release/state-management/tracked-properties.md
I have not vetted the entire document, but I didn't see any other obvious errors on cursory exam.
=> Several updates for clarity/typos.

guides/release/components/defining-a-component.md
Rafactor data-filename to classic layout and fix some typos #588
=> #588 components/defining-a-component

guides/release/components/component-basics.md
=> #588 components/components-basics

guides/release/testing/acceptance.md, guides/release/testing/testing-components.md, guides/release/testing/testing-controllers.md, guides/release/testing/testing-models.md, guides/release/testing/unit-testing-basics.md
=> Reading/Editing/Octaning “Testing” section

guides/release/templates/actions.md
This is in relation to issue https://github.com/emberjs/website/issues/3850
previously merged using pull request https://github.com/ember-learn/guides-source/pull/569
Updated the wrong file (face palm) :)
=> I added the change into the 3.7 source but not the release source.

guides/v3.7.0/contributing/adding-new-features.md
Minor changes for clarity and readability.
Went through all links to make sure they were still accurate.  No changes necessary here.
Part of Octane Guides review https://github.com/ember-learn/guides-source/issues/588
=> Grammatical fixes for "Contributing to Ember.js"

guides/release/pages.yml
This just removes a leftover merge conflict marker that made its way into the build 👍 
I have tested this locally and it does indeed fix the build 🎉
=> fixing the build

guides/release/models/index.md
- Update code samples to make use of new syntax
- Update file paths to be aligned with new project structure
=> #588 - octane - guides update - model/index

guides/release/tutorial/subroutes.md
Previous syntax gave error:  Invalid block parameters syntax
=> Fix syntax

guides/release/templates/actions.md
Sister PR to #640 which targets `master`
=> Replace a11y workaround with teaching a11y

config/environment.js
Should be merged after https://github.com/ember-learn/ember-website/pull/228
=> update url for the octane banner

CONTRIBUTING.md
In the `CONTRIBUTING.md`
/cc @locks @jenweber
=> Mention how to write a self-closing <Foo />

guides/release/object-model/computed-properties.md
=> Release Guides - missing instantiation in computed-properties

guides/release/working-with-javascript/classic-classes.md, guides/release/working-with-javascript/native-classes.md, guides/release/working-with-javascript/native-vs-classic-class-cheatsheet.md
=> Proofread 'Working with JavaScript' section of Octane preview guides

package-lock.json, package.json
Closes https://github.com/ember-learn/guides-source/issues/531.
=> update guidemaker-ember-template for LTS signifier in dropdown

guides/release/applications/services.md, guides/release/components/the-component-lifecycle.md, guides/release/object-model/classes-and-instances.md, guides/release/object-model/computed-properties-and-aggregate-data.md, guides/release/object-model/enumerables.md
=> Wrap arrays to avoid prototype extensions

guides/release/routing/defining-your-routes.md
Apparently I missed one spot. Part of #692.
=> Follow-up to #681

guides/release/tutorial/model-hook.md
Updated the built-in components to use angle bracket syntax. See https://github.com/ember-learn/guides-source/issues/692
=> Update docs for the built-in components for model-hook page

guides/release/testing/testing-components.md
=> Update docs for the built-in components for testing components page

guides/release/components/actions-and-events.md
This is part of https://github.com/ember-learn/guides-source/issues/692
=> Update docs for the built-in components for components/actions-and-events.md

guides/release/glossary/web-development.md
Fixes https://github.com/ember-learn/guides-source/issues/664.
=> Add CRUD to Glossary (#664)

guides/release/models/relationships.md
This is a clone of #634. However it needed two tiny fixes that I wasn't able to resolve before merge, so I opened a fresh PR.
This work is not mine and has already been reviewed, so I will self-merge.
=> #588 - octane - guides update - model/relationships 

MAINTAINERS.md
Hiya, just need a quick review on these instructions to do deployments. I'm sure that they are correct, just need a look for typos or anything that should be clearer. Thank you!
=> Maintainer docs - update guides-source deployment steps

versions.yml
Fixes https://github.com/ember-learn/guides-source/issues/738
=> Label 3.8 as LTS (#738)

guides/release/routing/defining-your-routes.md
This example uses Ember data in an action without any reference to it, maybe an example using fetch also? There was also a syntax error
=> Reference to ember data

guides/v3.8.0/tutorial/service.md
When I was going thru the tutorial, I was using windows. 
I would like to propose to include the windows-specific terminal command to set an environment variable for the leaflet maps api key.
=> Update SuperRentals tutorial - Service section

package-lock.json, package.json
Reverts ember-learn/guides-source#745
=> Revert "Bump ember-cli-netlify from 0.1.0 to 0.2.0"

guides/release/tutorial/autocomplete-component.md, guides/release/tutorial/service.md
=> Fix tutorial/autocomplete-component line additions for a code block. (Fixes #790)

guides/release/tutorial/service.md, guides/release/tutorial/subroutes.md
=> Patch - Fixes for #793

guides/release/ember-inspector/component-tree.md
=> Fix typo in Ember Inspector guide

guides/release/testing/testing-components.md
actual: >
Pretty Color: blue
expected: >
Pretty Color: green
=> Fix pretty-color test

guides/release/testing/index.md, guides/v3.1.0/testing/index.md, guides/v3.2.0/testing/index.md, guides/v3.3.0/testing/index.md, guides/v3.4.0/testing/index.md, guides/v3.5.0/testing/index.md, guides/v3.6.0/testing/index.md, guides/v3.7.0/testing/index.md, guides/v3.8.0/testing/index.md, guides/v3.9.0/testing/index.md
=> Fixes import on test example

guides/release/getting-started/intro.md
=> Fix broken links in guide.

app/index.html
=> [CHORE] Add fav-icon

guides/release/components/defining-a-component.md, guides/release/components/the-component-lifecycle.md, guides/release/components/triggering-changes-with-actions.md, guides/release/templates/input-helpers.md, guides/release/testing/testing-components.md
=> Labels accessibility

guides/release/models/finding-records.md, guides/release/models/index.md
Fixes #570 
1. Changed getJSON references to fetch in Models/ Finding records
2. Changed getJSON references to fetch in Models/ index
=> [CHORE] Refactor $.getJSON examples to use fetch

.remarkrc.js, guides/release/upgrading/editions.md
Same as #848 but it took some remark linter debugging to resolve the test failures. cc @kennethlarsen
=> Add links to Octane features + fix bullets

guides/release/routing/specifying-a-routes-model.md
=> migrate recent changes to class syntax

guides/release/reference/syntax-conversion-guide.md
Support for nested angle brackets was added in 3.10
fixes #879
=> Update angle bracket syntax for nested components

guides/release/applications/ember-engines.md
=> Sync ember-engines content with Ember Engines guides

app/router.js
was getting this deprecation while looking into something broccoli related. thought i would offer a fix. here is a reference that you lovely people maintain in some way :) https://deprecations.emberjs.com/v3.x/#toc_deprecate-router-events
=> [REFACTOR] Remove depreaction deprecate-router-events

guides/release/tutorial/acceptance-test.md
The original text implies that there can only be one assert in the test.
=> Update text for acceptance-test

.local.dic, guides/release/components/defining-a-component.md
This PR addresses the issue #428 in these manners:
- Explain how to use Ember CLI to create a nested component
- Explain where nested components live in the typical Ember folder structure
- Fix header levels
- Fix typos in code examples
=> Added explanation of nested components to Defining a Component

guides/release/upgrading/index.md
Adds a few relevant links from the upgrade guide to the deep dive.
Connects #876
=> Adds links to Octane Deep Dive from Octane Upgrade Guide

guides/release/templates/built-in-helpers.md
=> Removes mentions of capitalize

guides/release/tutorial/ember-data.md
Applying feedback so we can merge https://github.com/ember-learn/guides-source/pull/861/files
=> Sync examples with ember-data model generation

package-lock.json, package.json
This PR updates Guidemaker to remove the extraneous query parameters that were added to the network requests for json files. It also makes use of the ember-data store cache where it didn't before which will improve page loading speed 🎉 
This PR only updates a minor version of Guidemaker and it should not have any effect on stability but I would recommend a quick sense check of the Netlify preview before merging 👍
=> Updating Guidemaker

guides/release/getting-started/quick-start.md, guides/v2.13.0/getting-started/quick-start.md, guides/v2.14.0/getting-started/quick-start.md, guides/v2.15.0/getting-started/quick-start.md, guides/v2.16.0/getting-started/quick-start.md, guides/v2.17.0/getting-started/quick-start.md, guides/v2.18.0/getting-started/quick-start.md, guides/v3.0.0/getting-started/quick-start.md, guides/v3.1.0/getting-started/quick-start.md, guides/v3.10.0/getting-started/quick-start.md, guides/v3.2.0/getting-started/quick-start.md, guides/v3.3.0/getting-started/quick-start.md, guides/v3.4.0/getting-started/quick-start.md, guides/v3.5.0/getting-started/quick-start.md, guides/v3.6.0/getting-started/quick-start.md, guides/v3.7.0/getting-started/quick-start.md, guides/v3.8.0/getting-started/quick-start.md, guides/v3.9.0/getting-started/quick-start.md
=> adds aria role to clickable element

guides/release/applications/run-loop.md, guides/release/getting-started/index.md, guides/release/getting-started/intro.md, guides/release/getting-started/quick-start.md, guides/release/object-model/index.md, guides/release/tutorial/hbs-helper.md, guides/release/tutorial/index.md
Closes https://github.com/ember-learn/guides-source/issues/969.
=> Fix mentions of ES2015.

tests/acceptance/side-bar-links-test.js
=> Acceptance test for sidebar navigation links

guides/release/components/glimmer-components-dom.md, guides/release/getting-started/core-concepts.md, guides/release/getting-started/quick-start.md, guides/release/models/defining-models.md, guides/release/routing/controllers.md, guides/release/routing/specifying-a-routes-model.md, guides/release/state-management/tracked-properties.md, guides/release/templates/writing-helpers.md
Part of emberjs/rfcs#523 and emberjs/ember.js#18363.
Would love a review to see if I missed any prose in the nearby sections that needs to be updated as well.
=> Use `@model` named argument from route templates

guides/release/models/creating-updating-and-deleting-records.md, guides/release/models/customizing-adapters.md, guides/release/models/customizing-serializers.md, guides/release/models/defining-models.md, guides/release/models/finding-records.md, guides/release/models/pushing-records-into-the-store.md, guides/release/models/relationships.md, guides/release/object-model/classes-and-instances.md, guides/release/routing/specifying-a-routes-model.md, guides/release/tutorial/ember-data.md, guides/release/tutorial/installing-addons.md
=> Change ember-data URLs back to release

guides/release/configuring-ember/configuring-ember-cli.md
Reference cli config in CLI guides  per PR ember-learn/cli-guides#123
=> Reference CLI guide in CLI configuration section

app/styles/app.css
This is a spin off from https://github.com/ember-learn/guides-source/pull/1046#issuecomment-529172922, opening for discussion
=> Style improvements

.local.dic, guides/release/pages.yml, guides/release/state-management/computed-properties.md, guides/release/state-management/when-to-use-get-and-set.md
Updates the state management docs to match RFC 478
=> [FEAT] Updates State Management Docs

guides/release/testing/unit-testing-basics.md
=> Add section on stubs to unit testing basics

config/environment.js
Need to update this PR:
"Octane is almost here and you can make it better!"
Keep the language about its work-in-progress nature, and the link to the real prod guides.
=> update octane banner

guides/release/components/glimmer-components-dom.md, guides/release/upgrading/current-edition/glimmer-components.md
=> Switch to showing ember-modifier usage

guides/release/testing/index.md, guides/release/testing/test-types.md
While working on the next section for Testing (rules for writing tests), I realized I had made several mistakes in code examples. I'm hoping the changes will allow me/reader to smoothly transition to the next section.
=> Fixed code mistakes that I had made in testing pages

guides/release/components/index.md
First draft of documentation for nested component invocation(#1140). Wasn't sure where to add it, but I think the best place is close to the end of _Component Templates_.
=> Document nested component invocation #1140

guides/release/templates/input-helpers.md
Changed the checkbox input to a text input.
=> update input @type to equal "text" (#1016)

package-lock.json, package.json
=> update guidemaker-ember-template, closes #914

guides/release/configuring-ember/optional-features.md
=> Suggest adding ember-fetch when disabling jQuery

guides/release/applications/dependency-injection.md, guides/release/applications/services.md, guides/release/pages.yml
We missed this section when updating, adding it back for the time being.
=> Adds back Application Concerns

guides/release/components/template-lifecycle-dom-and-modifiers.md
Refresh of: https://github.com/ember-learn/guides-source/pull/1188 (PR got stale)
cc @knownasilya
=> docs: link to ref modifier

guides/release/getting-started/quick-start.md
I'm working on reading my way through the guides fairly comprehensively to help with prep for Octane. This PR cleans up a few loose ends I noticed while reading through the quick start
=> [Octane] Slight editorial pass on the quick start

guides/release/components/introducing-components.md
=> Clean up nested components info a tad

guides/release/upgrading/current-edition/index.md
* Suggest `npx @ember/octanify`
* Link to pre-existing optional features content
* Fix small typo
=> Tweak upgrade guide for Octane.

guides/release/routing/specifying-a-routes-model.md
The example given isn't syntactically correct and should be updated to use decorators as its more Octane-y :)
=> Use decorator to inject store service in example

guides/release/getting-started/anatomy-of-an-ember-app.md
=> Small typo in Components section

guides/release/getting-started/anatomy-of-an-ember-app.md
It felt like their were too many ambiguous uses of the pronoun "this" in this sentence, which is confusing in both code and english!
=> Rewording for clarification

guides/release/getting-started/index.md
Broken link to working with html css and javascript
=> docs: update link

guides/release/tutorial/part-1/working-with-data.md
=> Minor Typo

guides/release/components/component-state-and-actions.md
I'm not totally confident about the changes in here, but something is definitely off
=> Fix double it copy guides/release/components/component-state-and-actions.md

guides/release/routing/linking-between-routes.md
=> Fix each helper error

guides/release/configuring-ember/optional-features.md
I think the enable/disable bits on the `application-template-wrapper` feature are backwards.
=> Update application-template-wrapper documentation

guides/release/upgrading/current-edition/action-on-and-fn.md
=> fix typo in upgrade guide action-on-and-fn (#1259)

guides/release/getting-started/index.md, guides/release/getting-started/quick-start.md
=> Add a note about screen reader support

.github/workflows/tutorial-pull-requests.yml
`branches-ignore` was checking the base branch, not the head.
=> Tutorial ingestion should not fail the check

package-lock.json, package.json
Testing to see if my PR here fixes the issue described in https://github.com/ember-learn/guides-source/pull/1290 and https://github.com/empress/guidemaker/pull/38
=> Guidemaker version update

guides/release/components/block-content.md, guides/release/components/looping-through-lists.md, guides/release/components/template-lifecycle-dom-and-modifiers.md, guides/release/in-depth-topics/autotracking-in-depth.md, guides/release/in-depth-topics/patterns-for-actions.md, guides/release/in-depth-topics/patterns-for-components.md, guides/release/models/index.md, guides/release/services/index.md, guides/release/testing/testing-components.md, guides/v3.15.0/components/block-content.md, guides/v3.15.0/components/looping-through-lists.md, guides/v3.15.0/components/template-lifecycle-dom-and-modifiers.md, guides/v3.15.0/in-depth-topics/autotracking-in-depth.md, guides/v3.15.0/in-depth-topics/patterns-for-actions.md, guides/v3.15.0/in-depth-topics/patterns-for-components.md, guides/v3.15.0/models/index.md, guides/v3.15.0/services/index.md, guides/v3.15.0/testing/testing-components.md
additionally fixed a broken link 
from patterns-for-actions/ to autotracking-in-depth/
=> Colocation template file path fixes

guides/release/models/creating-updating-and-deleting-records.md
Remove unnecessary code for the example
=> Correct "deleteting records example"

guides/release/routing/redirection.md
Closes https://github.com/emberjs/ember.js/issues/14606
=> Add Zoey says note about query params when redirecting

guides/release/getting-started/quick-start.md
=> Include info about community in the quickstart

guides/release/upgrading/current-edition/tracked-properties.md
Follow up to https://github.com/ember-learn/guides-source/pull/1327 with the intended link in place.
=> Adding the proper link to list iteration

guides/release/addons-and-dependencies/index.md
Also updated reference to `package-lock.json` to include `yarn.lock`
=> fix: Update Ember CLI Sass link

guides/v3.16.0/in-depth-topics/patterns-for-actions.md
Fixes https://github.com/ember-learn/guides-source/issues/1349
=> Fix patterns for actions docs

guides/release/upgrading/current-edition/templates.md
Angle bracket component name fix. Have updated based on the component name used in the before code.
=> Guides angle bracket component name fix

guides/release/upgrading/current-edition/templates.md
=> Fixes indentation in code examples

.travis.yml, guides/release/addons-and-dependencies/index.md, public/images/ember-core-concepts/ember-core-concepts.svg
=> fix: further modernize core-concepts.svg

guides/release/accessibility/page-template-considerations.md
=> Show how to add a page title to routes (#1381)

.local.dic, guides/release/contributing/repositories.md
Fixes #1285 
-  Remove morph-range
-  Update Glimmer 2 and HTMLBars links
-  Link to help-wanted.emberjs.com
-  Link to community page
- Add some prose about kinds of contribution other than code
- Add `screencasting` to the dictionary to fix MD lint errors
=> chore: improve contributing page

guides/release/getting-started/quick-start.md, guides/v3.16.0/getting-started/quick-start.md
Fixes https://github.com/ember-learn/guides-source/issues/1389.
=> fix link from quick start to super rentals tutorial

.editorconfig, .eslintrc.js, .travis.yml, config/ember-cli-update.json, package-lock.json, package.json, testem.js
Closes https://github.com/ember-learn/guides-source/issues/1407
updated like this:
```
npm install -g ember-cli-update
ember-cli-update --to 3.16
```
=> update to Ember 3.16

README.md
I'm on a fresh machine and ran into this error
=> Update docs to mention Watchman

guides/release/configuring-ember/build-targets.md
Closes #1377
This should be merged/released after https://github.com/ember-learn/cli-guides/pull/163
=> Simplify Build Targets page and link to Ember CLI guides

guides/release/components/helper-functions.md
Fixes https://github.com/ember-learn/guides-source/issues/1418.
=> Add link to template helpers API docs

guides/release/configuring-ember/debugging.md
Fixes https://github.com/ember-learn/guides-source/issues/440.
=> update debugging examples to native class syntax

guides/release/accessibility/components.md, guides/release/components/component-state-and-actions.md, guides/release/components/index.md, guides/release/components/introducing-components.md
I edited 4 files for the button type fix. I will do others after this one is good. I would like to only edit 3 or 4 at a time. @locks maybe add an item to explain if the developer would need to specify the button type.
=> 1st wave of button type fix (#1416)

guides/release/components/looping-through-lists.md, guides/release/components/template-lifecycle-dom-and-modifiers.md, guides/release/getting-started/quick-start.md, guides/release/in-depth-topics/autotracking-in-depth.md
Please look these over and let me know if they are all correct. I committed each file separately in case I needed a change on one of them.
=> Add Button type (2)

guides/release/in-depth-topics/patterns-for-actions.md, guides/release/routing/controllers.md, guides/release/services/index.md, guides/release/testing/testing-components.md, guides/release/upgrading/current-edition/action-on-and-fn.md, guides/release/upgrading/current-edition/glimmer-components.md
This should fix all instances of <button> to <button type="button"> or <button type="submit">. 
Can someone look this over and either DM me on Discord or message me here. Thank you
=> Add Button Type (3)

MAINTAINERS.md, config/deploy.js.bak, package.json, scripts/update-search-index
I took some inspiration from https://blog.danslimmon.com/2019/07/15/do-nothing-scripting-the-key-to-gradual-automation/ and did a thing.
This moves the instructions regarding updating the search index for the Guides into a guided script, automating the steps that can be automated.
I tried to make it as non-destructive and straightforward as I knew how.
It isn't fancy in terms of error-recovery and such, but if we use the script I believe there's more likelihood of keeping it up to date, as the script would not work otherwise.
Opening for feedback!
=> Move manual search index updating to a guided script

guides/v3.11.0/getting-started/index.md
Updating the Watchman link. The previous one was broken.
=> Update Watchman Link

guides/release/models/customizing-adapters.md, guides/v3.15.0/models/customizing-adapters.md, guides/v3.16.0/models/customizing-adapters.md, guides/v3.17.0/models/customizing-adapters.md
Resolves ember-learn/guides-source#1444
=> Fix code example in Headers customization subsection

README.md
I updated `README.md` so that the contents are still relevant and are easy to understand for first-time contributors.
Some important changes are:
- Changed `Ember Guides Source` to an `h1`-level header
- Referred to the GitHub label `good first issue`
- Updated sentences to be concise and paragraphs to contain a small number of sentences
I recommend reviewing the commits one at a time. Each commit corresponds to updating one section.
Alternatively, you can [preview the final version](https://github.com/ember-learn/guides-source/blob/c4d5601c26034099233a81904e2ec887ea9d624f/README.md).
After approval and merge, we can squash-merge to keep 1 commit in the commit history.
=> Kept README up-to-date

guides/release/accessibility/page-template-considerations.md
@ijlee2 was correct! I didn't add the skip link illustration to the release as well. This PR is a continuation of #1487.
=> Add Skip Link Illustrations

guides/release/getting-started/index.md, guides/v3.15.0/getting-started/index.md, guides/v3.16.0/getting-started/index.md, guides/v3.17.0/getting-started/index.md, guides/v3.18.0/getting-started/index.md
I found the current Ember explanation to differ more than I expected from the approved headline on https://emberjs.com/
> # A framework for ambitious web developers.
> Ember.js is a productive, battle-tested JavaScript framework for building modern web applications. It includes everything you need to build rich UIs that work on any device.
So this PR adjusts the copy to be more in line with this text.
=> Adjusts Getting Started description of Ember

guides/v3.15.0/components/introducing-components.md, guides/v3.16.0/components/introducing-components.md, guides/v3.17.0/components/introducing-components.md, guides/v3.18.0/components/introducing-components.md, guides/v3.19.0/components/introducing-components.md
Follow-up PR to https://github.com/ember-learn/guides-source/pull/1503#pullrequestreview-460018277
=> Add missing "to"

guides/release/configuring-ember/debugging.md
Opening this after a copy paste fail. I think these need to be updated
=> fix semicolons

guides/release/getting-started/quick-start.md
I faced an Issue while creating a component tags in my app and later realised that i have to capitalise first letter of the word to make it work.
=> added component tag name convention [line 225]

guides/release/components/introducing-components.md
added following line on recomendation from @ijlee2
=> Updated introducing-components.md "" line[169]

guides/release/applications/run-loop.md, guides/release/getting-started/anatomy-of-an-ember-app.md, guides/v3.15.0/applications/run-loop.md, guides/v3.15.0/getting-started/anatomy-of-an-ember-app.md, guides/v3.19.0/applications/run-loop.md, guides/v3.19.0/getting-started/anatomy-of-an-ember-app.md
Let me know if there's anything I need to adjust on this PR
=> fixed typos

guides/release/getting-started/quick-start.md, guides/v3.15.0/components/introducing-components.md, guides/v3.15.0/getting-started/quick-start.md, guides/v3.16.0/applications/run-loop.md, guides/v3.16.0/components/introducing-components.md, guides/v3.16.0/getting-started/anatomy-of-an-ember-app.md, guides/v3.16.0/getting-started/quick-start.md, guides/v3.17.0/applications/run-loop.md, guides/v3.17.0/components/introducing-components.md, guides/v3.17.0/getting-started/anatomy-of-an-ember-app.md, guides/v3.17.0/getting-started/quick-start.md, guides/v3.18.0/applications/run-loop.md, guides/v3.18.0/components/introducing-components.md, guides/v3.18.0/getting-started/anatomy-of-an-ember-app.md, guides/v3.18.0/getting-started/quick-start.md, guides/v3.19.0/components/introducing-components.md, guides/v3.19.0/getting-started/quick-start.md, guides/v3.20.0/applications/run-loop.md, guides/v3.20.0/getting-started/anatomy-of-an-ember-app.md, guides/v3.20.0/getting-started/quick-start.md
In #1514, #1520, and #1527, we made changes to the `release` folder. I'd like to backport these changes to earlier Octane editions (`v3.15.0` to `v3.20.0`) for consistency.
I recommend reviewing commits one at a time. Each commit introduces the same type of change to 1 file across different version folders.
=> Backported recent PR changes

guides/release/getting-started/quick-start.md
"you will quickly discovered" => "you will quickly discover"
=> minor typo fix

guides/release/upgrading/current-edition/native-classes.md, guides/v3.15.0/in-depth-topics/native-classes-in-depth.md, guides/v3.15.0/models/defining-models.md, guides/v3.15.0/upgrading/current-edition/glimmer-components.md, guides/v3.15.0/upgrading/current-edition/native-classes.md, guides/v3.16.0/in-depth-topics/native-classes-in-depth.md, guides/v3.16.0/models/defining-models.md, guides/v3.16.0/upgrading/current-edition/glimmer-components.md, guides/v3.16.0/upgrading/current-edition/native-classes.md, guides/v3.17.0/in-depth-topics/native-classes-in-depth.md, guides/v3.17.0/models/defining-models.md, guides/v3.17.0/upgrading/current-edition/glimmer-components.md, guides/v3.17.0/upgrading/current-edition/native-classes.md, guides/v3.18.0/in-depth-topics/native-classes-in-depth.md, guides/v3.18.0/models/defining-models.md, guides/v3.18.0/upgrading/current-edition/glimmer-components.md, guides/v3.18.0/upgrading/current-edition/native-classes.md, guides/v3.19.0/in-depth-topics/native-classes-in-depth.md, guides/v3.19.0/models/defining-models.md, guides/v3.19.0/upgrading/current-edition/glimmer-components.md, guides/v3.19.0/upgrading/current-edition/native-classes.md, guides/v3.20.0/in-depth-topics/native-classes-in-depth.md, guides/v3.20.0/models/defining-models.md, guides/v3.20.0/upgrading/current-edition/glimmer-components.md, guides/v3.20.0/upgrading/current-edition/native-classes.md
@ijlee2 this is the pull request for issue `#1555`. it is ready to be reviewed.
=> Backport replacing part3

guides/v3.16.0/components/built-in-components.md, guides/v3.20.0/components/built-in-components.md
This PR closes https://github.com/ember-learn/guides-source/issues/1556.
=> Built in components updates #1556

guides/v3.15.0/components/built-in-components.md, guides/v3.17.0/components/built-in-components.md, guides/v3.18.0/components/built-in-components.md, guides/v3.19.0/components/built-in-components.md
=> Updates built-in-component section for older versions

guides/release/components/looping-through-lists.md, guides/v3.15.0/components/looping-through-lists.md, guides/v3.16.0/components/looping-through-lists.md, guides/v3.17.0/components/looping-through-lists.md, guides/v3.18.0/components/looping-through-lists.md, guides/v3.19.0/components/looping-through-lists.md, guides/v3.20.0/components/looping-through-lists.md
Cleaned up PR. for issue #1421
=> update triple curly brackets guidance issue #1421

guides/release/getting-started/index.md, guides/v3.15.0/getting-started/index.md, guides/v3.16.0/getting-started/index.md, guides/v3.17.0/getting-started/index.md, guides/v3.18.0/getting-started/index.md, guides/v3.19.0/getting-started/index.md, guides/v3.20.0/getting-started/index.md
=> Added links to CLI Guides in Getting Started

guides/v3.15.0/applications/run-loop.md, guides/v3.15.0/configuring-ember/disabling-prototype-extensions.md, guides/v3.15.0/getting-started/working-with-html-css-and-javascript.md, guides/v3.15.0/in-depth-topics/autotracking-in-depth.md, guides/v3.15.0/upgrading/current-edition/tracked-properties.md, guides/v3.16.0/applications/run-loop.md, guides/v3.16.0/configuring-ember/disabling-prototype-extensions.md, guides/v3.16.0/getting-started/working-with-html-css-and-javascript.md, guides/v3.16.0/in-depth-topics/autotracking-in-depth.md, guides/v3.16.0/upgrading/current-edition/tracked-properties.md, guides/v3.17.0/applications/run-loop.md, guides/v3.17.0/configuring-ember/disabling-prototype-extensions.md, guides/v3.17.0/getting-started/working-with-html-css-and-javascript.md, guides/v3.17.0/in-depth-topics/autotracking-in-depth.md, guides/v3.17.0/upgrading/current-edition/tracked-properties.md, guides/v3.18.0/applications/run-loop.md, guides/v3.18.0/configuring-ember/disabling-prototype-extensions.md, guides/v3.18.0/getting-started/working-with-html-css-and-javascript.md, guides/v3.18.0/in-depth-topics/autotracking-in-depth.md, guides/v3.18.0/upgrading/current-edition/tracked-properties.md, guides/v3.19.0/applications/run-loop.md, guides/v3.19.0/configuring-ember/disabling-prototype-extensions.md, guides/v3.19.0/getting-started/working-with-html-css-and-javascript.md, guides/v3.19.0/in-depth-topics/autotracking-in-depth.md, guides/v3.19.0/upgrading/current-edition/tracked-properties.md, guides/v3.20.0/applications/run-loop.md, guides/v3.20.0/configuring-ember/disabling-prototype-extensions.md, guides/v3.20.0/getting-started/working-with-html-css-and-javascript.md, guides/v3.20.0/in-depth-topics/autotracking-in-depth.md, guides/v3.20.0/upgrading/current-edition/tracked-properties.md
@ijlee2 this is the pull request for issue #1554. it is ready to be reviewed.
=>  Backport updating code examples (Part 2)

guides/release/contributing/repositories.md
This pull request closes https://github.com/ember-learn/guides-source/issues/1575.
=> Refresh for some links on the Repositories page

guides/release/components/component-state-and-actions.md
Added a learn more with links to Patterns for Components and Patterns for Actions in the main components section.
This pull request closes #1573.
=> Link to Patterns for Components and Actions from components section (#1573)

guides/release/applications/dependency-injection.md, guides/v3.15.0/applications/dependency-injection.md, guides/v3.16.0/applications/dependency-injection.md, guides/v3.17.0/applications/dependency-injection.md, guides/v3.18.0/applications/dependency-injection.md, guides/v3.19.0/applications/dependency-injection.md, guides/v3.20.0/applications/dependency-injection.md, guides/v3.21.0/applications/dependency-injection.md
Update examples to use the Octane syntax `@service`.  fixes #1473
=> Update service DI examples to use @service

config/environment.js
=> Removes 'Ember Octane is Here' banner

guides/release/applications/run-loop.md
Update the code snippet with the correct variable name
=> Bugfix: Update the code snippet with correct name

guides/release/testing/testing-components.md
https://github.com/ember-cli/ember-cli-qunit/issues/203#issuecomment-781547400
=> Added a note about stubbing the router service in non-application tests

guides/release/models/customizing-serializers.md
Believe this syntax is invalid.
=> Removed comma in Transform class example

guides/v3.15.0/models/customizing-serializers.md, guides/v3.16.0/models/customizing-serializers.md, guides/v3.17.0/models/customizing-serializers.md, guides/v3.18.0/models/customizing-serializers.md, guides/v3.19.0/models/customizing-serializers.md, guides/v3.20.0/models/customizing-serializers.md, guides/v3.21.0/models/customizing-serializers.md, guides/v3.22.0/models/customizing-serializers.md, guides/v3.23.0/models/customizing-serializers.md, guides/v3.24.0/models/customizing-serializers.md
=> Removed commas in Transform class examples

guides/release/models/customizing-serializers.md, guides/v3.15.0/models/customizing-serializers.md, guides/v3.16.0/models/customizing-serializers.md, guides/v3.17.0/models/customizing-serializers.md, guides/v3.18.0/models/customizing-serializers.md, guides/v3.19.0/models/customizing-serializers.md, guides/v3.20.0/models/customizing-serializers.md, guides/v3.21.0/models/customizing-serializers.md, guides/v3.22.0/models/customizing-serializers.md, guides/v3.23.0/models/customizing-serializers.md, guides/v3.24.0/models/customizing-serializers.md
=> Add missing attr import to custom transform example

guides/release/components/helper-functions.md
=> Add built-in helpers mention at the start of the helper page

guides/release/contributing/index.md
=> Update some Contributing to Ember sections

guides/release/accessibility/page-template-considerations.md, guides/release/getting-started/quick-start.md, guides/release/routing/defining-your-routes.md
https://github.com/ember-learn/guides-source/issues/1608
=> Use page-title helper from ember-page-title addon

guides/release/in-depth-topics/making-api-requests.md
This should probably be removed as it will only cause confusion, in my opinion.
What do other people think?
=> Remove sentence

tests/acceptance/visual-regression-test.js
This needs CI to actually have Percy run the tests. I tested that the list of names included all of the old ones and the new ones that I expected.
New names:
```
/index.html
/getting-started/index.html
/getting-started/quick-start/index.html
/getting-started/working-with-html-css-and-javascript/index.html
/getting-started/anatomy-of-an-ember-app/index.html
/tutorial/part-1/index.html
/tutorial/part-1/orientation/index.html
/tutorial/part-1/building-pages/index.html
/tutorial/part-1/automated-testing/index.html
/tutorial/part-1/component-basics/index.html
/tutorial/part-1/more-about-components/index.html
/tutorial/part-1/interactive-components/index.html
/tutorial/part-1/reusable-components/index.html
/tutorial/part-1/working-with-data/index.html
/tutorial/part-1/recap/index.html …
```
=> Recursively find pages to test with Percy

.local.dic, guides/release/getting-started/quick-start.md
Here's a draft to fix issue #1645 using _redirect.
=> Described adding _redirect file for deploying to Netlify

guides/release/upgrading/current-edition/tracked-properties.md, guides/v3.15.0/upgrading/current-edition/tracked-properties.md, guides/v3.16.0/upgrading/current-edition/tracked-properties.md, guides/v3.17.0/upgrading/current-edition/tracked-properties.md, guides/v3.18.0/upgrading/current-edition/tracked-properties.md, guides/v3.19.0/upgrading/current-edition/tracked-properties.md, guides/v3.20.0/upgrading/current-edition/tracked-properties.md, guides/v3.21.0/upgrading/current-edition/tracked-properties.md, guides/v3.22.0/upgrading/current-edition/tracked-properties.md, guides/v3.23.0/upgrading/current-edition/tracked-properties.md, guides/v3.24.0/upgrading/current-edition/tracked-properties.md, guides/v3.25.0/upgrading/current-edition/tracked-properties.md
Minor edit correcting a property name on an address Object, `this.address.state` to `this.address.region`
=> Fix Object property name

guides/release/contributing/index.md
=> docs: fix issue #1690 instructions to change API docs

guides/release/routing/defining-your-routes.md
Add missing article 'a' to the `defining-your-routes.md` guide.
=> Add missing article 'a'

guides/release/configuring-ember/embedding-applications.md
related to: https://github.com/ember-learn/guides-source/issues/1719
=> update code examples to use classes

guides/release/components/looping-through-lists.md, guides/v3.15.0/components/looping-through-lists.md, guides/v3.16.0/components/looping-through-lists.md, guides/v3.17.0/components/looping-through-lists.md, guides/v3.18.0/components/looping-through-lists.md, guides/v3.19.0/components/looping-through-lists.md, guides/v3.20.0/components/looping-through-lists.md, guides/v3.21.0/components/looping-through-lists.md, guides/v3.22.0/components/looping-through-lists.md, guides/v3.23.0/components/looping-through-lists.md, guides/v3.24.0/components/looping-through-lists.md, guides/v3.25.0/components/looping-through-lists.md, guides/v3.26.0/components/looping-through-lists.md
closes https://github.com/emberjs/ember.js/issues/19539
=> fixes typo in components -> looping-through-lists  example

guides/release/routing/preventing-and-retrying-transitions.md
Closes #1731 
Remove references to deprecated `willTransition` and add `routeWillChange`
@jenweber Please review
=> Refactor references to willTransition (#1731)

guides/v3.15.0/upgrading/current-edition/glimmer-components.md, guides/v3.16.0/upgrading/current-edition/glimmer-components.md, guides/v3.17.0/upgrading/current-edition/glimmer-components.md, guides/v3.18.0/upgrading/current-edition/glimmer-components.md, guides/v3.19.0/upgrading/current-edition/glimmer-components.md, guides/v3.20.0/upgrading/current-edition/glimmer-components.md, guides/v3.21.0/upgrading/current-edition/glimmer-components.md, guides/v3.22.0/upgrading/current-edition/glimmer-components.md, guides/v3.23.0/upgrading/current-edition/glimmer-components.md, guides/v3.24.0/upgrading/current-edition/glimmer-components.md, guides/v3.25.0/upgrading/current-edition/glimmer-components.md, guides/v3.26.0/upgrading/current-edition/glimmer-components.md, guides/v3.27.0/upgrading/current-edition/glimmer-components.md
see https://github.com/ember-learn/guides-source/pull/1738
=> ember-render-modifiers => @ember/render-modifiers back to ember@3.15

guides/release/components/index.md
If merged, this PR updates the code sample used to be accessible (the input is missing a label).
=> Update index.md for a11y 

guides/release/models/pushing-records-into-the-store.md, guides/release/routing/asynchronous-routing.md, guides/release/routing/defining-your-routes.md, guides/release/routing/loading-and-error-substates.md, guides/release/routing/preventing-and-retrying-transitions.md, guides/release/routing/query-params.md, guides/release/routing/redirection.md
Addresses some of the concerns in https://github.com/ember-learn/guides-source/issues/1711
=> Ember 4.0 preparation

guides/release/components/looping-through-lists.md
Fixes https://github.com/ember-learn/guides-source/issues/1756.
=> Replaces EmberArray with tracked property in "Looping through lists"

guides/release/upgrading/current-edition/tracked-properties.md
This section should be easier to find and read now.
I moved some things around and added more specifics. The only substantive change besides rearranging is specifically mentioning ember-data relationships.
=> Improve when to still use get and set

guides/release/configuring-ember/handling-deprecations.md
=> docs: Remove unused import

guides/release/testing/test-types.md
=> Grammar fix: test-types.md

.remarkignore
=> Spell checking - ignore guide versions before v3.28

.local.dic, guides/release/code-editors/index.md
and if you need multiple, one of, etc
=> Be clearer in the editors page about what the purpose of each plugin is

guides/release/components/helper-functions.md
Part of:
https://github.com/emberjs/ember.js/issues/20054
https://github.com/emberjs/rfcs/pull/866
=> Update helper guides to use regular functions

guides/release/models/relationships.md
partially addresses: https://github.com/ember-learn/guides-source/issues/1921
=> Remove use of pushObject on RecordArray and ManyArray

scripts/update-search-index
there was a minor difference in the script that I noticed when I was running the deployment
=> update minor details in the search index deployment script

.eslintrc.js, ember-cli-build.js, package-lock.json, package.json, scripts/update-prebuild.mjs
I'm just pushing this to share the work that I have done with the team. I'm pretty sure there is a blocker that will prevent us from shipping this 🤔
=> implement "update prebuilt guides" script

ember-cli-build.js, package-lock.json, package.json, scripts/update-prebuild.mjs
This is just some small prep before running the script again to add more prebuilt versions. I'm separating the PRs to make these real changes easier to review
Note: this knocks almost 3 minutes off our netlify build times and gets us just under the 5 mins mark 😍 
I ran this against the repo and opened #1933 so I've you're happy with this PR then you should merge that one too 👍
=> Update prebuilt versions

guides/release/addons-and-dependencies/index.md
RFC: https://github.com/emberjs/rfcs/pull/907
Implementation PR: https://github.com/ember-cli/ember-cli/pull/10287
Advancement: https://github.com/emberjs/rfcs/pull/932
Brings `pnpm` up to the same amount of relevance in the guides as `yarn`.
=> Mention the pnpm-lock.yaml

guides/v3.4.0/getting-started/quick-start.md
Some notes on my changes, as a complete and utter noob Almost every documentation I see nowadays [or startup guide] neglects to mention how anything connects, making it almost impossible for someone that isn't introduced via another method to get started. Doing the steps and learning this information is always very simple, so there's no reason for not hand-holding first time users [and therefore making it more complicated than it actually is].
In the first change, my goal was to more clearly define what "outlet" is, and what the route is. The sentence "...any nested route will be rendered in that place" on line 80 is given before a route is defined, and it certainly doesn't define an outlet. It's like me telling you a Pompadigdog is actually a large grey Hoosmacker. If you don't know …
=> Update quick-start.md 3-21-23

guides/release/routing/defining-your-routes.md
https://rfcs.emberjs.com/id/0774-implicit-record-route-loading
=> Update defining-your-routes.md to reflect RFC #774

guides/release/applications/dependency-injection.md
Fix for https://github.com/ember-learn/guides-source/issues/2004
=> docs: fix import as service

guides/release/configuring-ember/debugging.md
Discussed with @kategengler and @MinThaMie during the RFC review on 15th of May
=> Remove import Ember from 'ember';

.local.dic, guides/release/code-editors/index.md
Ember plug-in for CodeLobster IDE is added
=> Add CodeLobster IDE to code editors

guides/release/configuring-ember/disabling-prototype-extensions.md, guides/release/in-depth-topics/autotracking-in-depth.md, guides/release/routing/query-params.md, guides/release/services/index.md, guides/release/upgrading/current-edition/tracked-properties.md
=> Removing prototype extension usage and @ember/array in favor of tracked built ins

guides/release/getting-started/quick-start.md
This introduces feature-flagged use of template tag to the quick start page.
=> Converting more quick-start page content to use template tag

guides/release/tutorial/part-1/component-basics.md
This fixes several diffs which were marked as additions when they should have been deletions (or vice versa).
=> Fix improperly-applied diff highlighting
