guides/v3.1.0/models/pushing-records-into-the-store.md

ensure code example uses correct method

---

guides/v3.1.0/tutorial/autocomplete-component.md

**WHY**: the existing code diff highlights were confusing when going
through the tutorial.
**WHAT**:
- update diff to highlight *all* added lines in each section
- add diff highlighting and more lines to snippet where `triggerKeyEvent` and `fillIn` are added so provide more context on where in the file this happens.
- update snippet where 2nd integration test for component was added to
make it clearer that it is an entirely new test. Previously just one line was highlighted but the entire test is new when you are in this step of the tutorial.
Pic of BEFORE:
Pic of AFTER:

Improvements in code snippets for autocomplete-component tutorial

---

guides/v3.1.0/controllers/index.md

First draft in tackling #34 
[rendered](https://github.com/chrisrng/guides-source/blob/c32e24ae5a2e689e80ecfbd84c18e09c1dfc3cf1/guides/v3.1.0/controllers/index.md)

Update Controller Index

---

guides/v3.2.0/tutorial/model-hook.md

While working through the tutorial, I noticed that there exists a diff for a line that doesn't exist, causing `undefined` to be displayed.
Found on Safari 11.1.1 
Confirmed on Chrome  66.0.3359.181

Remove undefined Diff from articles each loop 

---

guides/v2.18.0/object-model/computed-properties-and-aggregate-data.md

todo's -> todos, '...the incomplete todos...' is plural

incorrect apostrophe removal

---

guides/v3.1.0/tutorial/service.md

Using that part of the code by just copying and pasting would cause an error because of some unwanted trailing slashes. Someone learning Ember would think that those are necessary and could take some time to realize it should not be there.

Removing unwanted trailing slashes on sample code

---

guides/v2.10.0/applications/run-loop.md
guides/v2.11.0/applications/run-loop.md
guides/v2.12.0/applications/run-loop.md
guides/v2.13.0/applications/run-loop.md
guides/v2.14.0/applications/run-loop.md
guides/v2.15.0/applications/run-loop.md
guides/v2.17.0/applications/run-loop.md
guides/v2.18.0/applications/run-loop.md
guides/v2.2.0/applications/run-loop.md
guides/v2.3.0/applications/run-loop.md
guides/v2.4.0/applications/run-loop.md
guides/v2.5.0/applications/run-loop.md
guides/v2.6.0/applications/run-loop.md
guides/v2.7.0/applications/run-loop.md
guides/v2.8.0/applications/run-loop.md
guides/v2.9.0/applications/run-loop.md
guides/v3.0.0/applications/run-loop.md
guides/v3.1.0/applications/run-loop.md
guides/v3.2.0/applications/run-loop.md
guides/v3.3.0/applications/run-loop.md
test/helpers/getBadLineBreaks.js
test/link-checker.js

It looks like #15 didn't _quite_ cover @jenweber's work outlined in #12. Specifically, detecting bad line breaks in the Markdown docs (see link to MDN docs Arrow function):
This PR adds a failing test with a helper that detects those bad line breaks using the RegExp recommendations from https://github.com/ember-learn/guides-source/issues/12#issuecomment-357822393, and fixes the affected run-loop docs.

Repair bad line breaks for Markdown links

---

guides/v1.13.0/models/index.md
guides/v2.16.0/testing/testing-models.md
guides/v2.17.0/testing/testing-models.md
guides/v2.18.0/testing/testing-models.md
guides/v3.0.0/testing/testing-models.md
guides/v3.1.0/testing/testing-models.md
guides/v3.2.0/testing/testing-models.md
guides/v3.3.0/testing/testing-models.md

Noticed these were wrong, when I copied and pasted them and got errors. We should also probably removed references to `DS.Model` elsewhere, and always use these imports, but just wanted to fix what was broken for now.

Fix incorrect imports from ember-data

---

guides/v3.2.0/tutorial/subroutes.md

A random "/" on line 229 of `guides/v3.2.0/tutorial/subroutes.md`. Not sure if it was on purpose but I am going to think its just a syntax error because of a typo!

Typo in guides/v3.2.0/tutorial/subroutes.md line 229

---

guides/v3.2.0/models/finding-records.md

This change adds `.then()` to `findRecord` and `findAll` examples and moves the comment on the end of the line to the previous line which should also help by removing the need to scroll towards the right to see that lil tidbit.

Differentiate when a promise/record is returned

---

guides/v3.1.0/templates/binding-element-attributes.md

Previously submitted as https://github.com/emberjs/guides/pull/2132
The Guides currently advise to use `Component.reopen` to add attribute bindings to bundled components, such as `LinkComponent` and `TextField`. However this practise is now discouraged.
This PR updates this advice to recommend that users override these components instead.
Note that I have had to remove the text field example, as it requires overriding the undocumented `-text-field` component.
Here's a Twiddle with an example: https://ember-twiddle.com/0feff0577066c1414747aef04202aa9d?openFiles=templates.application.hbs%2C

Where to add attribute bindings

---

guides/v3.0.0/templates/writing-helpers.md
guides/v3.1.0/templates/writing-helpers.md
guides/v3.2.0/templates/writing-helpers.md
guides/v3.3.0/templates/writing-helpers.md

Fix examples bug on writing-helpers.md

---

guides/v3.3.0/object-model/classes-and-instances.md
guides/v3.3.0/object-model/computed-properties.md

Attempt to check off task 2 in https://github.com/emberjs/guides/issues/2303 and update some of the language around `get` and `set`, including when to and when not to use it.
@jenweber please have a look. might conflict slightly with #122

updates more `get` instances and language in object model

---

guides/v3.3.0/tutorial/ember-cli.md

Having two instances of `node_modules` in markdown triggers an unwanted conversion to italics for all the text inbetween

Escape underscore in to prevent unwanted italics

---

guides/v3.3.0/object-model/computed-properties.md

* Attempt to improve the language around the details of using object references and properties as dependents keys on computed property.
* Updates the example code to use something slightly more interesting than `foo bar`.
@jenweber could use some stylistic proof reading.
resolves #82

improves description on objects as computed property dependents keys

---

guides/v3.3.0/testing/acceptance.md

The `context` parameter was removed from `find` and `findAll` in `ember-test-helpers`. Currently, trying to use it will get you an exception, as can be seen in this PR: https://github.com/emberjs/ember-test-helpers/pull/358 That's the first of these two commits.
Since I was at it, I added a second commit to try make the formatting less awkward. Currently it tries to be a definition list formatted as nested lists, but doesn't really achieve that. From the Showdown documentation[1], I see that the correct way to do that would be with 4 spaces, rather than the current 2. However I went to see what this would look like if instead I put both term+definition in a single list item:
Thoughts?
[1] Nested lists with Showdown: https://github.com/showdownjs/showdown/wiki/Showdown's-Markdown-syntax#nes …

The `context` parameter is no more (+formatting)

---

guides/v3.4.0/models/finding-records.md

Incorrect link: http://emberjs.com/api/data/classes/DS.Store.html#method_peekAll
Correct link: https://www.emberjs.com/api/ember-data/release/classes/DS.Store/methods/findAll?anchor=peekAll

Correct the link to `store.peekAll()` method

---

guides/v3.4.0/routing/defining-your-routes.md

I just found myself stuck because I forgot this empty argument (seems like the router interprets the path as a dynamic segment). The error seems intentionnally not thrown, and hard to track down: https://github.com/tildeio/router.js/blob/73d6a7f5ca6fba3cfff8460245fb5a3ceef8a2b5/lib/router/transition-intent/named-transition-intent.ts#L214)

Adding note for transitionning to a wildcard route

---

guides/v2.18.0/tutorial/routes-and-templates.md
guides/v3.0.0/tutorial/routes-and-templates.md
guides/v3.1.0/tutorial/routes-and-templates.md
guides/v3.2.0/tutorial/routes-and-templates.md
guides/v3.3.0/tutorial/routes-and-templates.md
guides/v3.4.0/tutorial/routes-and-templates.md

The URLs here have a trailing slash, considered part of the anchor, which results
in the link taking a user to the top of the doc page, rather than the specific
anchored method within the doc page.
Remove the trailing slash, so the anchor is accurate, and the user is taken
directly to the appropriate method in the doc page.

routes-and-templates: Fix anchor parameters in documentation links.

---

guides/v3.4.0/components/passing-properties-to-a-component.md
guides/v3.4.0/components/triggering-changes-with-actions.md

First draft for [#162](https://github.com/ember-learn/guides-source/issues/162)

Improve explanation of passing actions (#162)

---

guides/v3.4.0/tutorial/autocomplete-component.md

The tutorial mistakenly uses 'rental-listing' in the 'list-filter-test.js'
test module description string. Correct it, to match what the end user
would see after generating the test for this component.

autocomplete-component.md: Fix test module string description.

---

guides/v2.0.0/components/defining-a-component.md

One code block was unclosed, so it was messing up the rendering for the rest of the page on your docs site.

Fix formatting errors

---

guides/v3.4.0/tutorial/autocomplete-component.md

It's not possessive. (get it? ha ha)

autocomplete-component: Correct contraction grammar.

---

guides/v3.4.0/routing/query-params.md

First draft. Highlights difference that current routing sections speaks about routing query params and directs to information on using query params with Ember Data.

Highlighted difference between query params (#158)

---

guides/v3.5.0/templates/built-in-helpers.md

* Add guide for `array` helper (addresses https://github.com/emberjs/ember.js/issues/17052)
* Updated the rest of the guide to use the "one line per sentence" convention.

Add guide for `array` helper

---

guides/v3.5.0/templates/actions.md

Fixed a typo for the handle bars template. It should be {{body}} instead of {{{body}}}

Fixed a typo for the handle bars template

---

guides/v3.5.0/routing/query-params.md

While working with {{link-to}} helper and query param today, I hit issue https://github.com/emberjs/ember.js/issues/16867.
I couldn't find a sample example to see why query param was getting set as undefined. Looks like that is the expected behavior based on the comment in the thread.
Hence updated the documentation to make it more clearer.

Updated documentation for query-param scope

---

guides/v3.5.0/models/finding-records.md

It seems for me that Ember.Enumerable was used in older releases of Ember. Currently link to https://emberjs.com/api/ember/release/classes/Ember.Enumerable just returns 404.

fixed referencing old Ember.Enumerable

---

guides/v3.0.0/models/finding-records.md
guides/v3.1.0/models/finding-records.md
guides/v3.2.0/models/finding-records.md
guides/v3.3.0/models/finding-records.md
guides/v3.4.0/models/finding-records.md

additionally to https://github.com/ember-learn/guides-source/pull/221 I've updated guides back to 3.0.0 when MutableArray arrived.

fixed broken link from Ember.Enumerable to MutableArray

---

CONTRIBUTING.md
guides/v2.10.0/index.md
guides/v2.11.0/index.md
guides/v2.12.0/index.md
guides/v2.13.0/index.md
guides/v2.14.0/index.md
guides/v2.15.0/index.md
guides/v2.16.0/index.md
guides/v2.17.0/index.md
guides/v2.18.0/index.md
guides/v2.2.0/index.md
guides/v2.3.0/index.md
guides/v2.4.0/index.md
guides/v2.5.0/index.md
guides/v2.6.0/index.md
guides/v2.7.0/index.md
guides/v2.8.0/index.md
guides/v2.9.0/index.md
guides/v3.0.0/index.md
guides/v3.1.0/index.md
guides/v3.2.0/index.md
guides/v3.3.0/index.md

As mentioned a week ago on Discord, now I finally came around to fixing all the slack links to discord
I hope this is still needed.

Replaced Slack links with Discord in old guides and Contributing

---

guides/v3.5.0/tutorial/simple-component.md

I was going through this tutorial today, and found 2 lint errors for the `rental-listing.hbs` file:
Not sure if this is the best way to fix the no-invalid-interactive error, but hope this is helpful.

Fix lint errors for rental-listing.hbs

---

guides/v3.4.0/components/the-component-lifecycle.md
guides/v3.5.0/components/the-component-lifecycle.md

This fixes #197, fixes #198 and fixes #199.
I'm not 100% sure if we should be using the date picker example anymore, but I kept it as a straight conversion right now in order for the diffs to be easier to see and review.

Remove jQuery from component lifecycle

---

guides/v3.5.0/models/index.md

The change splits the section `What are Ember Data models?`  in two parts:
- `What are Ember Data models?`
- `Ember Data flexibility`
I described the reasons for this change on the [`When to add Ember Data` discussion](https://discuss.emberjs.com/t/when-to-add-ember-data/15050/14).
> Some folks decided to provide a JSON-API backend because Ember Data uses it as a default format, and this added more work for them. I think extending the REST adapter and use a conventional REST backend would have been a better choice for them. 
This made me think how the documentation of the default format of Ember Data  is communicated or may be interpreted. 
@jenweber suggested creating small incremental PRs, so this is a small change to highlight more the existing content around the "Flexibility" …

Add `Ember Data flexibility` section

---

guides/v3.5.0/tutorial/simple-component.md

On the Building a Simple Component page, we jump right into building a
component without defining what a component is or what they are use for.
This change adds a brief definition (the same one used in
https://guides.emberjs.com/v3.5.0/components/defining-a-component/) and
a reason why the user might want to use them.
in #245.

Defines what a component is and is used for

---

guides/v3.5.0/tutorial/ember-cli.md

When the application template is first introduced, we should make note
of what its purpose is, namely, as the main layout template for the
entire app.
in #245.
Also, I reformatted some overly long lines in the rest of the document.

Addresses the purpose of the application.hbs

---

guides/v3.5.0/components/block-params.md

This seems to be the only place where we talk of using components in `non-block` form. From my experience, and looking at other pages, `inline` seems to be the most prevalent term used to describe this.
I'm updating this here for consistency.
Some examples from the docs:
- [link-to docs](https://guides.emberjs.com/release/templates/links/#toc_using-link-to-as-an-inline-component)
- [`component` helper docs](https://emberjs.com/api/ember/release/classes/Ember.Templates.helpers/methods?anchor=component)

[Docs] Replace `non-block` with `inline`

---

guides/v3.5.0/tutorial/installing-addons.md

On the Installing Addons page, we instruct the user to restart the
server. This change makes those instructiosn explicit.
in #245.

Explicitly states how to restart the server

---

guides/v3.5.0/tutorial/routes-and-templates.md

On the Routes & Templates page, in the An Index Route section, the
paragraphs starting at "All we want to do..." present too much
ancillary information. This change simplifies it to focus on just the
beforeModel() hook and the replaceWith() function.
in #245.

Simplifies the "All we want to do..." portion

---

guides/v2.10.0/tutorial/simple-component.md

On the Building a Simple Component page, we should explicitly call out
that properties of components are available to their templates. This
change does so.
in #245.

Clarifies where template properties come from

---

guides/v2.10.0/tutorial/simple-component.md

In Building a Simple Component, we mention Handlebars templates but
never state what Handlebars is. This change adds a brief paragraph to
describe Handlebars, link to a more robust explanation ([Handlebars
Basics](https://guides.emberjs.com/release/tutorial/simple-component/)), and explain the relationship between templates and component
source files.
in #245.

Adds Handlebars explainer paragraph

---

guides/v3.5.0/models/index.md

Previously discussed at #240 
The PR moves the content of the `JSON-API on Ember Data` to the `Ember Data Flexibility` section and remove the rest of the content of the `Convention Over Configuration with JSON API`.
@jenweber commented:
> The JSONAPI section was probably written when the project was brand-new. I have a feeling that we can keep the same content level with fewer words, now that the project is better established and known.
I tried to reformulate the content a bit, but I ended up removing the rest of the `Convention Over Configuration with JSON API`, feel free anyone to suggest any better form.

Models: reformulate the JSON/API content 

---

guides/v2.10.0/tutorial/simple-component.md
guides/v2.11.0/tutorial/simple-component.md
guides/v2.12.0/tutorial/simple-component.md
guides/v2.13.0/tutorial/simple-component.md
guides/v2.14.0/tutorial/simple-component.md
guides/v2.15.0/tutorial/simple-component.md
guides/v2.16.0/tutorial/simple-component.md
guides/v2.17.0/tutorial/simple-component.md
guides/v2.18.0/tutorial/simple-component.md
guides/v2.3.0/tutorial/simple-component.md
guides/v2.4.0/tutorial/simple-component.md
guides/v2.5.0/tutorial/simple-component.md
guides/v2.6.0/tutorial/simple-component.md
guides/v2.7.0/tutorial/simple-component.md
guides/v2.8.0/tutorial/simple-component.md
guides/v2.9.0/tutorial/simple-component.md
guides/v3.0.0/tutorial/simple-component.md
guides/v3.1.0/tutorial/simple-component.md
guides/v3.2.0/tutorial/simple-component.md
guides/v3.3.0/tutorial/simple-component.md
guides/v3.4.0/tutorial/simple-component.md
guides/v3.5.0/tutorial/simple-component.md

This removes the following JSLint violation `Unnecessary string concatenation. Use {{rental.image}} instead of "{{rental.image}}".  no-unnecessary-concat`.

Remove no-unnecessary-concat jslint violation

---

guides/v3.6.0/addons-and-dependencies/managing-dependencies.md

Some spellcheck tests were merged in prior to merging #326, which caused a failure on merge. This fixes the spelling issue (organisation -> organization)

spelling fix

---

guides/v3.6.0/templates/built-in-helpers.md

Remove docs for array-helper

---

guides/v3.7.0/components/block-params.md
guides/v3.7.0/components/customizing-a-components-element.md
guides/v3.7.0/components/defining-a-component.md
guides/v3.7.0/components/handling-events.md
guides/v3.7.0/components/passing-properties-to-a-component.md
guides/v3.7.0/components/the-component-lifecycle.md
guides/v3.7.0/components/triggering-changes-with-actions.md
guides/v3.7.0/components/wrapping-content-in-a-component.md
guides/v3.7.0/getting-started/core-concepts.md
guides/v3.7.0/getting-started/quick-start.md
guides/v3.7.0/pages.yml
guides/v3.7.0/reference/syntax-conversion-guide.md
guides/v3.7.0/templates/angle-bracket-syntax.md
guides/v3.7.0/templates/built-in-helpers.md
guides/v3.7.0/testing/index.md
guides/v3.7.0/testing/testing-components.md
guides/v3.7.0/tutorial/autocomplete-component.md
guides/v3.7.0/tutorial/ember-cli.md
guides/v3.7.0/tutorial/service.md
guides/v3.7.0/tutorial/simple-component.md
guides/v3.7.0/tutorial/subroutes.md

Here is the base of the angle bracket notation conversion. There are a few things that will need addressed:
Need a new image for /images/ember-core-concepts/ember-core-concepts.png to convert <RentalTitle>
`tutorial/simple-component` and `components/defining-a-component` :
Update:  "A dash is required in every component name to avoid conflicting with a possible HTML element, so rental-listing is acceptable but rental isn't."
Are these correct?
```
{{#each this.model as |post|}}
<BlogPost @post.title @post.body/>
{{/each}}
```
```
<MyComponent @people={{array
'Tom Dade'
'Yehuda Katz'
this.myOtherPerson}}
/>
```

Convert to angle bracket notation in version 3.7

---

guides/v3.7.0/templates/handlebars-basics.md

Add `this.` to value examples since the are used in the example above.

guides(templates): consistent use of `this`

---

guides/v3.7.0/templates/built-in-helpers.md

This is just a quick (optional) extension to https://github.com/ember-learn/guides-source/pull/375 that I wanted to propose and didn't want to slow down the merge process with a "change request" or comment. 
Essentially I think it might be a slightly better experience if we link people to the index page of the helpers so they can easily see everything that is available.
@jenweber if you don't agree then feel free to reject/close this PR 👍

templates: updated built-in-helpers link to point at the index

---

guides/release/components/defining-a-component.md
guides/release/tutorial/simple-component.md

@mansona I closed #420 in favor of this new PR because I didn't realize my local guides-source forked repo was so far behind upstream when I rebased. The rebase ended up cluttering the commit history for #420, so it just seemed easier/cleaner to open this new PR with the same changes.
@jenweber this adds the Angle Bracket Syntax callouts discussed previously in a few locations.
@locks not sure if you want to take a look since it references the syntax guide that you're updating in #401. 
FWIW the callouts don't seem to accept using MD links (the message body of the cta-note is a `<p>` tag), so I used `<a>` tags instead.
This is how it's looking:
AND

Add a few callouts to Angle Bracket Syntax

---

guides/release/components/passing-properties-to-a-component.md

Addresses #431 by explaining why we are showing classic invocation syntax for positional params.

Add note about positional params requiring classic syntax

---

guides/release/reference/accessibility-guide.md

For the the "application template wrapper" links, I'm not sure where these were intended to point. I'd be happy to change the target.
From just the current text, it's not clear how one would disable this feature. I added a codeblock for handy copy-pasting.
This PR is mostly just a note that the links were broken. Feel free to close it if some other solution makes sense.

Accessibility Guide: improve guidance for disabling application template wrapper

---

guides/release/pages.yml

If merged into the octane branch, this PR resolves issue #393 by re-ordering the table of contents (as outlined in RFC 431).

Issue 393 - TOC rearranging

---

guides/release/tutorial/acceptance-test.md

In the Ember tutorial for [Planning Your App](https://guides.emberjs.com/release/tutorial/acceptance-test/), there's a missing closing quotation for the `tests/acceptance/list-rentals-test.js` JavaScript block.

Added missing quotation for 'Acceptance | list rentals'

---

guides/release/testing/testing-components.md

I was under the impression that module test names should contain `-` in the component name, shouldn't they?

Add dashes to test module names

---

guides/release/tutorial/service.md

Fix typo reference to variable in service test example (#506)

---

guides/release/tutorial/service.md

Fixes #347 
Adds stub service to integration test so that leaflet ajax calls don't happen during test run.

Tutorial stub service to prevent ajax

---

guides/release/routing/defining-your-routes.md

In Defining Your Routes > Wildcard / globbing routes, there is a code sample that's intended to illustrate a promise with a success and error callback, but both are written with `then`:
This seems to be a bug, because the second `then` would receive a successful result from the first `then`, not an error. It seems that `catch` is intended instead. This PR corrects that:

Fix error callback written with then instead of catch

---

guides/release/routing/specifying-a-routes-model.md

Specifying a Route's Model > Dynamic Models had a few unnecessary slashes in parenthetical statements:
This PR removes them:

Remove unnecessary slashes

---

guides/release/applications/run-loop.md
guides/release/components/triggering-changes-with-actions.md
guides/release/models/customizing-adapters.md
guides/release/models/index.md
guides/release/models/pushing-records-into-the-store.md
guides/release/routing/asynchronous-routing.md

Previously the guides in some places had "Ajax", others "ajax", and others "AJAX". As discussed in #518, this PR standardizes on the capitalization "Ajax", which seems to be the most accepted.
Code references to `$.ajax()` are not changed, of course.

Standardize 'Ajax' capitalization

---

guides/release/components/block-params.md
guides/release/components/wrapping-content-in-a-component.md
guides/release/pages.yml
guides/release/reference/syntax-conversion-guide.md
guides/release/tutorial/autocomplete-component.md

This fixes the node-tests which are failing due to file rename
changes like:
1. passing-properties-to-a-component =>
passing-arguments-and-html-attributes
2. triggering-changes-with-actions => adding-actions
https://github.com/ember-learn/guides-source/issues/540#issuecomment-468694994

[TEST FIXES] Test case failures due to file rename changes

---

guides/release/routing/asynchronous-routing.md
guides/release/tutorial/autocomplete-component.md
guides/release/tutorial/service.md
package-lock.json

Closes https://github.com/ember-learn/guides-source/issues/237.
@ppcano can you :eyes:?

remove unnecessary mentions of RSVP

---

guides/release/getting-started/core-concepts.md
guides/release/getting-started/quick-start.md

Fixes #541
1. Change Route example to class syntax in core concepts
2. Change PeopleList component to use class syntax
3. didRender example to class syntax

[OCTANE] [CHORE] Quickstart JS to use Class Syntax #541

---

guides/release/state-management/index.md
guides/release/state-management/patterns-for-state.md
guides/release/state-management/tracked-properties.md

Fixes a couple links in State Management Guide: https://github.com/ember-learn/guides-source/pull/536
I didn't get to all of them and can create an issue if we want to track.
@pzuraq I think  broccoli-static-site-json or whatever converts the guides markdown does not support reference style links.

start fixing a few links in state management

---

guides/release/templates/handlebars-basics.md

This is a rough draft that should not be merged yet. It is for evaluating what, if any, of this content could come into the Guides.
> To make Templates work as the opening topic, additions are necessary in the introduction.
This PR partially addresses https://github.com/ember-learn/guides-source/issues/460

New Templates intro

---

guides/release/templates/handlebars-basics.md

* Updates naming of positional and named arguments for helpers
* Explains that templates are compiled before referencing "the compiler"
* Adds an `@` to the component template example showing "referencing an argument passed in to the component"
* Tweaks verbiage of "Nested Helpers" section to refer to nested helper invocation
* Tweaks "Ember's templates" to "Templates in Ember" (specifically because they are "glimmer templates" not "ember templates")

Small tweaks to handlebars-basics.md

---

guides/release/templates/actions.md
guides/release/templates/binding-element-attributes.md
guides/release/templates/built-in-helpers.md
guides/release/templates/displaying-the-keys-in-an-object.md
guides/release/templates/handlebars-basics.md
guides/release/templates/writing-helpers.md

Re: https://github.com/ember-learn/guides-source/issues/588
/cc @pzuraq @jenweber

Review and Octanify the template guides

---

guides/release/working-with-javascript/classic-classes.md
guides/release/working-with-javascript/native-classes.md
guides/release/working-with-javascript/native-vs-classic-class-cheatsheet.md

This is an attempt at fixing minor issues with the octane "Working with JavaScript" guides.
see https://github.com/ember-learn/guides-source/issues/588

docs(working-with-javascript): fix minor typos and invalid JavaScript

---

guides/release/getting-started/quick-start.md
guides/release/services/services.md

I've made what I hope are corrections to the code in these two sections. However, there are a few questions:
1. Are components referred to as `all-rentals` or as `<AllRentals />` when just mentioning them in the text? In these sections, the former is used.
2. The image in "Core Concepts" uses classic curlies when invoking the `rental-title` component. IMO this is *precisely* where (in something aimed at newcomers) angle brackets should be used.
3. Services looked untouched for octane? I corrected as much of the code as I could, but I don't know how to do this:
```
cart: computed(function() {
return getOwner(this).lookup('service:shopping-cart');
})
```

#588 Reading of "Getting Started" and "Services"

---

guides/release/data-management/index.md
guides/release/pages.yml

This just fixes the last 404 guide that is missing from the Table of contents

[OCTANE] Fixing missing guide

---

app/styles/app.css

Addressing #611 by hiding edit pencil and the search bar.

[Octane] CSS hacks to hide the edit pencil and the search bar

---

guides/release/testing/testing-components.md

I just learned the semi-colon's are optional after the class definition and methods so it doesn't *really* matter. Though, I've observed most examples in the octane branch do not include them so I think it is best to make the style consistent. @maciej-ka so don't take my nit picking over semi colons personally 😄 
We could continue @mansona's work (https://github.com/ember-learn/guides-source/pull/589#issue-260513096) and automate prettifying the code snippets.

[OCTANE] remove double semi, other semi colon

---

guides/release/components/actions-and-events.md

I learned a lot reading through this, I would like some review in the first paragraph. #588

#588 components/actions-and-events

---

guides/release/components/yields.md

#588 components/yields

---

app/router.js
public/robots.txt

I think this resolves the blocker for standing up `octane-guides-preview.emberjs.com`
closes #610

Adjust robots.txt and Google Analytics for staging deployment

---

guides/release/components/contextual-components.md

#588 components/contextual-components

---

guides/release/templates/actions.md

We should teach how to write accessible apps, not work around
a11y features.
Sister PR to https://github.com/ember-learn/guides-source/pull/639 which targets `octane` instead

Fixes bad advice for non-interactive elements

---

guides/release/components/actions-and-events.md
guides/release/components/arguments-and-attributes.md
guides/release/components/component-basics.md
guides/release/components/glimmer-components-dom.md
guides/release/getting-started/quick-start.md
guides/release/pages.yml
guides/release/reference/accessibility-guide.md
guides/release/reference/syntax-conversion-guide.md
guides/release/routing/asynchronous-routing.md
guides/release/routing/defining-your-routes.md
guides/release/routing/loading-and-error-substates.md
guides/release/routing/preventing-and-retrying-transitions.md
guides/release/routing/query-params.md
guides/release/routing/redirection.md
guides/release/routing/rendering-a-template.md
guides/release/routing/specifying-a-routes-model.md
guides/release/state-management/patterns-for-state.md
guides/release/state-management/tracked-properties.md
guides/release/templates/built-in-helpers.md
guides/release/templates/handlebars-basics.md
guides/release/upgrading/editions.md
guides/release/working-with-javascript/native-classes.md
package-lock.json

There's more work to do to hide unfinished content, but this is a good stopping point for someone to review.
See the commit logs for a summary of the work that was done. This includes converting Routes to clas syntax.
I need someone to look over the use of `super` in `loading-and-error-substates.md`:
```javascript
setupController(controller, error) {
console.log(error.message);
super(...arguments);
}
```
As well as in general `query-params.md` because I have questions about whether these things need some kind of decorator like tracked.
#633

Convert Routes to Native Classes and hide unfinished content

---

guides/release/components/component-basics.md

This PR updates the route `/release/components/component-basics` for #588

[OCTANE] Update component-basics

---

guides/release/configuring-ember/configuring-your-app.md
guides/release/configuring-ember/handling-deprecations.md

* Configuring Your App - I did some serious re-wording here
* Configuring Ember CLI - Left as is
* Handling Deprecations - Just cleaned up a header. This should probably be reconsidered / balanced with the existence of the "upgrading/deprecations" guide entry.

Review "configuring" (part one)

---

guides/release/upgrading/editions.md

This was a really strange issue with the Markdown 🙈 
Apparently if you start the \`\`\`js code blocks with an indentation before the backticks you need to add an **extra** indent for the code.
Here is an example: 
```handlebars
- `classNameBindings`
Before:
```js
import Component from '@ember/component';
export default Component.extend({
classNameBindings: ['darkMode:dark-mode'],
darkMode: false,
text: 'Hello, world!',
});
\```
```
👆 will not work
You need an extra indent in the code block like this: 
```handlebars
- `classNameBindings`
Before:
```js
import Component from '@ember/component';
export default Component.extend({
classNameBindings: ['darkMode:dark-mode'],
darkMode: false,
text: 'Hello, world!',
});
\```
```
It is subtle but we must appease our Markdown overlords 🙈

[OCTANE] fixing the rendering of the code examples in lists on upgrading/editions

---

guides/release/getting-started/quick-start.md

Fixes #655, hopefully in a way that doesn't require too much re-working of associated content
This template change avoids encouraging readers to use click event listeners w/ non-focusable and non-interactive elements
```diff
<h2>{{this.title}}</h2>
<ul>
{{#each this.people as |person|}}
-    <li>{{person}}</li>
+    <li>
+      <button {{action "showPerson" person}}>{{person}}</button>
+    </li>
{{/each}}
</ul>
```

Octane: Quickstart a11y improvements

---

guides/release/upgrading/editions.md

Because this example is showing how to create defaulted args, it should actually use them.

Fix arg defaults example

---

guides/release/getting-started/quick-start.md

As written the quickstart doesn't display the list of scientists after adding PeopleList component.
The new `@` syntax appears to be required.

quickstart not working: fix component syntax to use @

---

guides/release/routing/defining-your-routes.md
guides/release/routing/preventing-and-retrying-transitions.md
guides/release/templates/binding-element-attributes.md
guides/release/templates/links.md

Per [RFC #459](https://emberjs.github.io/rfcs/0459-angle-bracket-built-in-components.html), we need to update the Octane guides to use `<AngleBracket />` invocation syntax for the built-in components: `<Input />`, `<Textarea />` and `<LinkTo />`.
The feature has landed (behind a feature flag) in ember.js in https://github.com/emberjs/ember.js/pull/17735 (`<Input />`, `<Textarea />`) and https://github.com/emberjs/ember.js/pull/17772 (`<LinkTo />`). The API docs have not been updated yet, but the RFC text and the tests should be a good enough reference for the time being.
In this PR, I started the work by converting the main `<LinkTo />` guide, which is probably the trickiest.  I preserved the flow of the guide but updated the content to fit the new API whenever it makes sense.
I would …

Angle bracket <BuiltIn /> components

---

guides/release/components/block-params.md

The examples used `this.post` in component templates to refer to a passed in `post` arg.
This change updates the examples to use `@post` (named arg).
If this is a premature considering that we're still pre-octane, perhaps `this.` should just be omitted, since use of `this.` potentially confuses things since there's no backing js example shown?

use named args

---

.gitignore
extractCode.js
package-lock.json
package.json

I don't know how useful this would be going forward but if we want to have it available we could think about merging this in some way 🤔 I think for now we should leave this PR open and decide what to do with it in a more general way later 👍 
If anyone wants to use this script in another branch you can just run the following: 
```
git checkout extract-code-script extractCode.js
npm i gfm-code-blocks
```
And then you can run: 
```
node extractCode.js
``` 
and it will export all of the code samples into a `code` directory

add script for extracting code blocks

---

guides/release/tutorial/subroutes.md

Update the subroute page of the guides to use angle bracket invocation for link-to helper.
(Part of #692)

Update subroute guides to use angle bracket built-ins

---

guides/release/tutorial/simple-component.md

Updated the built-in components to use angle bracket syntax. See https://github.com/ember-learn/guides-source/issues/692
_Feeling a bit of deja vu..._

Update docs for the built-in components for simple-component page

---

guides/release/routing/query-params.md

Update docs for the built-in components in `routing/query-params.md`

---

guides/release/tutorial/autocomplete-component.md

Updated the built-in components to use angle bracket syntax. See #692

Angle-bracket-ize tutorial/autocomplete-component.md

---

guides/release/upgrading/editions.md

Updated the built-in components to use angle bracket syntax. See https://github.com/ember-learn/guides-source/issues/692

Updating upgrading editions.md

---

guides/release/components/actions-and-events.md

This sentence was never rewritten from the current guides. The `target` attribute is no longer used in Octane, so the last part of the sentence can be removed.

[OCTANE] Components/Actions and Events: Remove reference to the "target" attribute

---

guides/release/contributing/repositories.md

In https://guides.emberjs.com/release/contributing/repositories/, add ember-cli to the list of main repositories

Add ember-cli to the list of main repositories

---

.gitignore
guides/release/routing/specifying-a-routes-model.md

See https://github.com/ember-learn/guides-source/issues/20 for the motivation. In short, in order to make Ember Data guides a standalone resource and learning concept, we need to refactor how we teach data fetching in other parts of the app. I've made this article longer, and I don't take that lightly, but based on my experience teaching others, we can't skimp on this. Understanding models is one of the greatest new learner pain points, so more examples and simpler language are critical.
If there are controversial refactors, I can break this into multiple PRs, but I think it's best evaluated as a whole.
This PR is a broad refactor of https://guides.emberjs.com/release/routing/specifying-a-routes-model/
- Read this entire PR comment first
- Read my version and see if it checked all the …

Refactor "Specifying a route's model" to be agnostic of data library choice

---

guides/release/testing/testing-models.md

Seems, URL for Ember Data Tests are moved to another place and hence updating it with right URL

Update the URL link for Ember Data Tests hyperlink

---

guides/release/models/customizing-serializers.md

fix #565. I did a quick search and didn't find other obvious examples.
There could be more and this can easily happen without automating
linting or formatting the files before a commit (prettier). See
https://github.com/ember-learn/guides-source/blob/master/extractCode.js
for initial work.

unify code fence examples to JSON

---

guides/release/applications/dependency-injection.md
guides/release/controllers/index.md
guides/release/models/relationships.md
guides/release/routing/query-params.md
guides/release/services/index.md
guides/release/templates/built-in-helpers.md
guides/release/testing/index.md
guides/release/testing/testing-controllers.md
guides/release/testing/testing-models.md
guides/release/testing/testing-routes.md

This is incremental work towards #669

Octane - Replace some references to Computed Properties with Tracked

---

guides/release/components/defining-a-component.md
guides/release/state-management/index.md
guides/release/upgrading/editions.md

If you're someone with push access to my PR, please feel free to edit directly whenever possible by adding commits rather than comments. It's much appreciated!
Here's what I changed, broadly speaking:
- Remove references to components as "glimmer components"
- Remove most of the sections explaining editions, since it's covered in our new main site pages
- Added some more structure. Each major section has "benefits" and "getting used to..."
- Edited for conciseness where possible
- Fixed up some small accessibility things
- reformatted very long bulleted lists
- took out typescript reference
If this seems good, I can follow up with a second pass that aims to replace about half the code examples with links to existing sections in the Guides. I think many of the sections of the Components …

Revising the Octane Upgrade Guide

---

guides/release/routing/redirection.md
guides/release/templates/input-helpers.md

Also added labels to form inputs, partially addresses #798

Finish converting link-to and input to angle brackets

---

guides/release/testing/testing-models.md

Recent refactor of inline URL link's overrides the correct URL which was changes early.

Update Ember Data Test link to correct URL

---

guides/release/tutorial/autocomplete-component.md

* add missing `settled` import in list-filter.js for autocomplete-component guide
going through the (release) guide and just fixing some typos

Fix typo in release guide

---

.local.dic
guides/release/pages.yml
guides/release/upgrading/cheat-sheet.md
guides/release/upgrading/index.md

Create an Octane upgrade strategy guide

---

guides/release/components/actions-and-events.md
guides/release/models/relationships.md

One is of a semicolon where a colon should be used ({ inverse: true }), and
the other imports from @ember/component despite the fact that all of the
other component section pages import from @glimmer/component.

Two small typos.

---

.local.dic
guides/release/components/customizing-a-components-element.md
guides/release/components/defining-a-component.md
guides/release/components/the-component-lifecycle.md
guides/release/components/triggering-changes-with-actions.md
guides/release/models/index.md
guides/release/routing/defining-your-routes.md
guides/release/routing/preventing-and-retrying-transitions.md
guides/release/routing/query-params.md
guides/release/routing/redirection.md
guides/release/routing/specifying-a-routes-model.md
guides/release/templates/binding-element-attributes.md
guides/release/templates/input-helpers.md
guides/release/templates/links.md
guides/release/testing/testing-components.md

Update link-to, input, and textarea to angle bracket invocation

---

guides/v3.9.0/tutorial/service.md

Hi there, request you to review my change and merge so that the tutorial for beginners learning ember can't be tiresome. For a new guy trying to learn ember and reaching upto the services tutorial is a great journey but if that person is working on windows he/she may get misleaded with code snippets which won't be accepted by WINDOWS OS

add tutorial command correction for windows (#863)

---

guides/release/templates/links.md

The model property was supposed to reference the photo variable.

LinkTo documentation incorrectly had an attribute value as a string rather than interpolated variable

---

guides/release/templates/built-in-helpers.md

component template usages were missing the @ symbol, and missing a reference to the argument name

fix templating built-in-helpers examples

---

guides/release/components/glimmer-components-dom.md

The `{{#if this.showingHelp}}` condition is used in the following template and is not needed inside of the `Modal` component itself.

octane/glimmer-components-dom: Fix broken `Modal` template

---

guides/release/components/glimmer-components-dom.md

The output diff code had failed to show that the attribute is changed, instead only showing the text changing as in a previous example. Updated the code to show both attribute and text changing with appropriate diff markup.

Fix output diff for "Manipulating Attributes" example

---

guides/release/components/handling-events.md

As per https://github.com/emberjs/rfcs/blob/master/text/0486-deprecate-mouseenter.md

Remove deprecated events

---

guides/release/configuring-ember/optional-features.md

Closes https://github.com/ember-learn/guides-source/issues/925
Document the optional features:
* application-template-wrapper
* template-only-glimmer-components

Doc optional features "application wrapper" and "template only components"

---

guides/release/templates/writing-helpers.md

Removed invalid closing parenthesis.  
Output message:
```javascript
Unexpected token (6:2)
4 | export function makeBold([param, ...rest]) {
5 |   return htmlSafe(`<b>${param}</b>`);
> 6 | });
|  ^
7 | 
8 | export default helper(makeBold);
--------------------------------------------------------------------------------
```

Update typos writing-helpers.md

---

guides/release/components/actions-and-events.md
guides/release/state-management/tracked-properties.md
guides/release/upgrading/editions.md

I feel like saying that tracked properties are merely properties that "change in value over time" is a bit unclear. I've tried to add language that indicates that `@tracked` is for properties that change not "over time" but over the lifetime of their owner/component. I'm not sure the language I'm using is quite right, however.

Making @tracked scope more explicit

---

guides/release/reference/syntax-conversion-guide.md

(This PR targets the `octane` branch).
And some light copy-editing.
Unified capitalization of "angle bracket syntax" to be lowercased throughout.
Fixes #929

"classic" -> "curly" in syntax-conversion-guide

---

guides/release/components/glimmer-components-dom.md

Changed `{{ref "audioElement" this}}` to `{{ref this "audioElement"}}` as per addon's deprecation.
https://github.com/lifeart/ember-ref-modifier#deprecations

Updated `ember-ref-modifier` syntax

---

guides/release/models/defining-models.md

I just was working with someone on the help channel on Discord who had hit snags based around setting up an `ideas` model (with adapter/serializer) instead of an `idea` model. Thought it might be worth clarifying in the docs that the standard approach here is to go with a singular name

Add a note about ED singular usage naming

---

guides/release/testing/testing-components.md

- The build complains that there's no close to `<Input>`.
- The linter complains about single quotes in handlebars.
- The linter complains about the `{{#each}}` indentation.
Incidentally I cannot get this test to pass in a fresh Ember 3.11.1 app. I tried running the tests in Chrome, CLI, Firefox, Safari. No matter what I do it appears that the `dispatchEvent` does not cause the `fetchResults` function to be called. I can't tell if this is because `dispatchEvent` won't trigger that or if `@fetchResults={{this.fetchResults}}` is not attaching the handler properly or some other problem.

Fix asynchronous action component test example

---

.github/workflows/tutorial-ingestion.yml

The [CI job](https://travis-ci.org/ember-learn/super-rentals-tutorial) from the [super-rentals-tutorial repo](https://github.com/ember-learn/super-rentals-tutorial) will [automatically](https://github.com/ember-learn/super-rentals-tutorial/pull/6) build and push changes to the [`super-rentals-tutorial`](https://github.com/ember-learn/guides-source/commits/super-rentals-tutorial) branch.
This workflow will automatically open a PR (like #1009) whenever there are changes to that branch for review.
This process ensures that we review the final markdown content for any accidental hiccups, before merging them into the [octane branch](https://github.com/ember-learn/guides-source/commits/octane).

Automatically ingest Octane tutorial content

---

guides/release/templates/input-helpers.md

I think checkbox event names should be defined in camelCase format.

[DOCS] Update input-helpers.md

---

.github/workflows/dummy.yml

This is needed, because if we didn't have any workflow on the master branch, GitHub thinks that we are not using the feature and will not run any workflows on this repo (that may exists on other branches).
Based on my testing, this seems to be sufficient. This workflow will probably never run in practice, but that seems to be sufficient.
Replaces #1017

Add a dummy workflow to the master branch

---

guides/release/routing/specifying-a-routes-model.md

Easily missable typo I think! The section after that one _does_ use a `photo` route.

Fix wrong filename in "Specifying a Route's Model" page

---

app/styles/app.css

1. Make lines with "+"/"-" align with other lines by shifting them to the left by one character to compensate.
2. Make the "+"/"-" non-selectable and non-copyable with CSS pseudo elements.
Before:
After:
This may want to be upstreamed to guidemaker? It could also have avoided generating those `.diff-operators` to begin with.

Fix code blocks diff rendering

---

.github/workflows/tutorial-ingestion.yml

That is thanks to https://github.com/ember-learn/super-rentals-tutorial/commit/4d31c9f25e89cf483423881c085c17a6f741fc89

PSA: You may now delete the `super-rentals-tutorial` branch after merging PRs

---

app/styles/app.css

Using `position: relative; left: -1ch;` had a very mild side effect that when you make text selection, the browser seems a tad confused bout how to draw the highlight color.
It doesn't affect the selection/copy/paste functionality, as far as I can tell, just looks a bit odd visually. It occured to me there may be another way to pull the text to the left without that problem so here it is.
It seems to work the same, but does not have the selection rendering issue.
Before (Safari on OS X):
Before (Chrome on OS X):
After (Safari on OS X):
After (Chrome on OS X):

Fix diff format (take 2)

---

guides/v3.10.0/routing/defining-your-routes.md

Fixes [#1054 ](https://github.com/ember-learn/guides-source/issues/1054)
This PR fixes the typo in the referred template name for the example route `/posts/123`.

Fix template filename typo in router guides page

---

guides/release/routing/defining-your-routes.md

Fixes [#1060 ](https://github.com/ember-learn/guides-source/issues/1060)
This PR fixes the typo in the referred template name for the example route /posts/123.

Fix template filename typo in router guides page (v3.12.0 - release)

---

guides/v3.11.0/routing/defining-your-routes.md

Fixes [#1059 ](https://github.com/ember-learn/guides-source/issues/1059)
This PR fixes the typo in the referred template name for the example route /posts/123.

Fix template filename typo in router guides page (v3.11.0)

---

guides/release/upgrading/editions.md

This updates the edition guide with a general editting pass,
and to make sure that all of the information within it is
accurate with the latest changes (e.g. tracked property
interop has changed slightly)

Updates the edition guide to match the latest changes

---

.travis.yml

With this PR we get deploys to master on merges and preview apps for PRs if they're successful. We'll have to look at the travis deploy step logs to get the url for now.
I've reorganized the build steps so that we save a few mins in each build.

Deploy from travis

---

guides/release/tutorial/autocomplete-component.md
guides/release/tutorial/hbs-helper.md

This changes two pieces of content in the Ember Tutorial which confused me in their respective sections. First, one of the examples in `hbs-test.md` uses an arbitrary example name `my-helper` in a test name, while Ember actually generates the test with the proper name `rental-property-type`. Second, there was a mistake in the `autocomplete-component.md` section where the `settled` function is imported without a diff marker at the place where it's used, getting rolled into the diff marker for the next section.
To test this change, I verified that `npm run lint:md` passes. 
Let me know if you'd like any more detail!

Corrections to content in Tutorial

---

.travis.yml

Our preview deploys started timing out. This fixes it, I think?
We have run out of Percy requests for the month, which is unfortunate but will be fine.

increase travis wait time

---

guides/release/components/glimmer-components-dom.md
guides/release/models/defining-models.md
guides/release/models/index.md
guides/release/object-model/enumerables.md
guides/release/templates/actions.md
guides/release/testing/index.md

Fix for issue #1124 .
The remaining non-empty `alt` instances happen in `release/tutorial` (will be fixed separately) and in pre-Octane Guides.

Removed alternate texts for Zoey & Tomster images in the release version

---

guides/release/tutorial/service.md

alt tag should be descriptive and not just a static generic string such as 'image'.
Using `this.location.title`
src: https://a11yproject.com/posts/alt-text/

Updated alt img tag for a11y (#1056)

---

guides/release/configuring-ember/optional-features.md

- Feature **enabled**: a wrapping `<div>` is created.
- Feature **disabled**: no wrapping `<div>` is created.

Fix configuration logic of `application-template-wrapper`

---

package-lock.json
package.json

Closes #1137 
We were seeing old table of contents entries showing up in newer versions, if you switched between versions! See https://github.com/empress/guidemaker/pull/26

update guidemaker, fix bug in #1137

---

guides/release/components/index.md

I think this is the right branch?
Tested this locally by running the app and `Working With JavaScript` now renders as expected instead of going to dead link.

[fix] update link to Working With JavaScript in Defining a Component guide

---

guides/release/routing/query-params.md

LinkTo closing tag is invalid in examples. Spotted by @JavaLavaMT

(typo) fix closing LinkTo tag

---

config/environment.js

Since Octane will not be 3.14, we need to update this banner.
Details: https://blog.emberjs.com/2019/10/31/octane-release-update.html

update octane banner

---

guides/v1.10.0/models/the-rest-adapter.md

There's a bug on the REST Adapter page that has to do with rendering markdown on the page. There was an extra space before the backticks that close out the last code block in the relationships section of that page (link [here](https://guides.emberjs.com/release/models/the-rest-adapter/#toc_relationships)), which messes up the formatting on the rest of the page.

Fix broken markdown on REST Adapter page

---

guides/release/routing/defining-your-routes.md
guides/v2.10.0/routing/defining-your-routes.md
guides/v2.11.0/routing/defining-your-routes.md
guides/v2.12.0/routing/defining-your-routes.md
guides/v2.13.0/routing/defining-your-routes.md
guides/v2.14.0/routing/defining-your-routes.md
guides/v2.15.0/routing/defining-your-routes.md
guides/v2.16.0/routing/defining-your-routes.md
guides/v2.17.0/routing/defining-your-routes.md
guides/v2.18.0/routing/defining-your-routes.md
guides/v2.3.0/routing/defining-your-routes.md
guides/v2.4.0/routing/defining-your-routes.md
guides/v2.5.0/routing/defining-your-routes.md
guides/v2.6.0/routing/defining-your-routes.md
guides/v2.7.0/routing/defining-your-routes.md
guides/v2.8.0/routing/defining-your-routes.md
guides/v2.9.0/routing/defining-your-routes.md
guides/v3.0.0/routing/defining-your-routes.md
guides/v3.1.0/routing/defining-your-routes.md
guides/v3.10.0/routing/defining-your-routes.md
guides/v3.11.0/routing/defining-your-routes.md
guides/v3.12.0/routing/defining-your-routes.md
guides/v3.2.0/routing/defining-your-routes.md
guides/v3.3.0/routing/defining-your-routes.md
guides/v3.4.0/routing/defining-your-routes.md
guides/v3.5.0/routing/defining-your-routes.md
guides/v3.6.0/routing/defining-your-routes.md
guides/v3.7.0/routing/defining-your-routes.md
guides/v3.8.0/routing/defining-your-routes.md
guides/v3.9.0/routing/defining-your-routes.md

`:model-name_id` implies that a multiword model would be dasherized with `_id` appended at the end. I think this is incorrect?
This doesn't work with the [routes-segments-snake-case lint rule](https://github.com/ember-cli/eslint-plugin-ember/blob/master/docs/rules/routes-segments-snake-case.md) which will complain about the dash in the dynamic segment, and it also means that you'd need to use `params['blog-post_id']` instead of `params.blog_post_id` which I don't think was intended by the original author here.

Change `:model-name_id` to `:model_name_id` in defining routes doc

---

guides/release/tutorial/simple-component.md

I was following the Ember.js tutorial and noticed that the diff misses a delete marker for the closing brackets of the module function in the code sample (last line).
Ref. https://guides.emberjs.com/release/tutorial/simple-component/#toc_an-integration-test

Fix simple component integration test code sample diff

---

guides/release/routing/specifying-a-routes-model.md

Not sure about all things, so please correct me if I'm wrong.

fix some inconsistencies

---

app/helpers/includes.js
app/initializers/patch-page-service.js
app/styles/app.css
app/templates/components/table-of-contents.hbs
guides/release/pages.yml
tests/acceptance/side-bar-links-test.js
tests/acceptance/visual-regression-test.js

Adds the ability to have ToC headings, which allows us to organize the ToC visually.
Unlike the previous nesting work, this is purely presentational. Headings do not link to any page, and they do not need to be toggled. This just allows us to bucket the main sections more clearly.
Could use help with the styling, I think I landed on something _ok_ but it could use more work.

[FEAT] Adds ToC Headings

---

guides/release/components/index.md

The `Restrictions` section listed 3 items:
```
- Only valid HTML elements in a `<body>` tag can be used
- No `<script>` tags
- You can only use HTML that is valid in `<body>`
```
I believe the first and third ones are identical and the list can be reduced to:
```
- Only valid HTML elements in a `<body>` tag can be used
- No `<script>` tags
```

Remove duplicate restriction about valid HTML elements in <body>

---

guides/release/components/block-content.md
guides/release/components/component-arguments-and-html-attributes.md
guides/release/components/conditional-content.md
guides/release/components/helper-functions.md
guides/release/components/introducing-components.md

These are some very slight editorial tweaks to what otherwise reads quite nicely. My goal here was to reduce jargon and simplify the language a tad without over-simplifying the items we're teaching

[Octane] Slight tweaks to the new component guides

---

guides/release/configuring-ember/optional-features.md

This should add a section documenting the use of the [default async observer optional feature](https://github.com/emberjs/ember-optional-features/blob/master/features/default-async-observers.js) as described in RFC#494: https://github.com/emberjs/rfcs/pull/494

upd(configure:ember): add writeup on default-async-observers

---

guides/release/in-depth-topics/autotracking-in-depth.md

Noticed that the getter was using `this._cache` as a method and not a POJO.

[Autotracking In-Depth] Fix typo in Autotracking code example

---

.travis.yml
guides/release/applications/applications-and-instances.md

The goal of this PR is for Travis to show a failure if the build fails, but otherwise display success, even if netlify times out.
If this works, I think we can repurpose the should-deploy script to make deploys skippable.

Try to fix missing netlify reporting

---

guides/release/pages.yml

I noticed that the title for https://guides.emberjs.com/release/components/template-lifecycle-dom-and-modifiers/ has a typo.

Fixed a typo (lifecyle -> lifecycle)

---

guides/release/configuring-ember/disabling-prototype-extensions.md

The method `includes()` used on the native JS Array should be changed to something else, to a method that really does not exist.
1. You are trying to show that this method does not exist but at this time [native JS Array does implements the `includes()` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes).
2. The snippet currently displayed is incorrect and should return `true`:
```js
let islands = ['Oahu', 'Kauai'];
islands.includes('Oahu');
// => true
```

docs: update Array method when compared to EmberArray

---

.local.dic
guides/release/testing/test-types.md
guides/release/testing/testing-components.md
guides/release/testing/testing-helpers.md

Some of the integration test docs are using the deprecated `ember-cli-htmlbars-inline-precompile` in code examples. This patch updates the docs to use the preferred `ember-cli-htmlbars` instead.

Use ember-cli-htmlbars over deprecated ember-cli-htmlbars-inline-precompile

---

guides/release/applications/dependency-injection.md
guides/release/applications/ember-engines.md
guides/release/applications/index.md
guides/release/applications/run-loop.md
guides/release/components/built-in-components.md
guides/release/components/helper-functions.md
guides/release/components/looping-through-lists.md
guides/release/configuring-ember/disabling-prototype-extensions.md
guides/release/configuring-ember/handling-deprecations.md
guides/release/configuring-ember/optional-features.md
guides/release/ember-inspector/data.md
guides/release/models/finding-records.md
guides/release/object-model/bindings.md
guides/release/object-model/classes-and-instances.md
guides/release/object-model/computed-properties-and-aggregate-data.md
guides/release/object-model/computed-properties.md
guides/release/object-model/enumerables.md
guides/release/object-model/index.md
guides/release/object-model/observers.md
guides/release/routing/asynchronous-routing.md
guides/release/routing/defining-your-routes.md
guides/release/routing/loading-and-error-substates.md
guides/release/routing/redirection.md
guides/release/routing/rendering-a-template.md
guides/release/routing/specifying-a-routes-model.md
guides/release/services/index.md
guides/release/testing/testing-components.md
guides/release/upgrading/current-edition/native-classes.md

I noticed the links didn't all go to the latest api docs, so I corrected them mechanically in the release guides via the snippet below
```sh
git grep -l ember\/3 guides/release | xargs perl -pi -w -e 's/ember\/3\.\d+/ember\/release/g;'
```

Fix all release links to release API

---

guides/release/components/block-content.md
guides/release/components/conditional-content.md
guides/release/components/helper-functions.md
guides/release/components/looping-through-lists.md
guides/release/routing/linking-between-routes.md
guides/release/tutorial/part-2/ember-data.md

Each is individually applicable
- Typo in guides/release/routing/linking-between-routes.md
- Fix typos guides/release/components/looping-through-lists.md
- Correct examples from copy; guides/v3.9.0/templates/built-in-helpers.md
- Consider clarifying guides/release/components/block-content.md
On first read I didn't catch that the error dialog component was being
called `ErrorDialog`
- Typo in guides/release/components/block-content.md
- Typo in guides/release/components/conditional-content.md
- ~~Typo in guides/release/tutorial/part-2/ember-data.md~~  moved to https://github.com/ember-learn/super-rentals-tutorial/pull/122

A number of copy fixes in the release (Octane) guides

---

guides/release/components/built-in-components.md

I ended up just testing this in the browser.
Reading through the api docs, old guides, and glimmer code I wasn't exactly
sure what this example is trying to say or if it's just wrong.

Clarify unclear checkbox event example

---

guides/v3.3.0/models/customizing-adapters.md

The url would actually be `https://api.emberjs.com/api/1/people/1`.

fix namespace example

---

app/styles/app.css
guides/release/components/index.md

Adds a link to the HTML5 specification with the full list of void elements.
Also fixes a syntax bug where Markdown backticks were used (and not rendered as intended) inside the HTML block, replacing them with `code` tags. Additionally, fixes the CSS to remove the incorrect orange background styling of `code` elements inside the red background of the Zoey CTA.

Add link to full list of void HTML elements

---

guides/release/services/index.md

This cleans up the services guide a bit and includes one fix.
Changes:
* fix: use `A()` to initialize items in shopping-cart service (it's currently imported, but never used)
* make improvements to verbiage for clarity and correctness including:
* more specificity (decorator vs. function)
* more correctness (decorated property vs. variable key)
* a note explaining `inject as service`
* remove extraneous semicolons after class definitions
* replace tabs with spaces in one code example so it indents properly when rendered

Clean up services

---

guides/release/models/defining-models.md

The example above uses `PersonModel`. Figured this example should be consistent.

Adds Model suffix

---

guides/release/models/customizing-adapters.md

The section "Endpoint Path Customization" contains an example of how to costumize the JSONAPIAdapter adapter namespace used.
The URL shown is missing part of the namespace specified in the example.

Fixed "Endpoint Path Customization" example

---

.remarkignore

Reduced the number of entires by globing old major versions vs individual releases.  This will make it easier to maintain the file over the long term.

Simplify remark ignore file

---

guides/release/components/conditional-content.md

Co-Authored-By: @gokatz 
Both of us skimmed right past the inline form because the first examples don't show the syntax to use. This adds a section to the top for people looking for quick answers.

Improve if documentation

---

guides/release/components/built-in-components.md

- This PR touches _only_ section on built-in-components.
- If we're talking about _components arguments_ AND the property name is in `backticks`, make sure there is always `@` symbol in front of the argument name.
- If we're talking about property that can be expressed as a _HTML attribute_, make sure we are _not_ using `@` symbol in front of the attribute name.
fix for: #1286

HTML Attributes vs Component Arguments

---

package-lock.json
package.json

Our index routes were 404s, which caused very long or failing requests for subsequent resources. This was fixed in guidemaker 2.2.0
Fixes https://github.com/ember-learn/guides-source/issues/1312
Fixes https://github.com/ember-learn/guides-source/issues/1266

index routes take 6s to load in prod - update guidemaker

---

guides/release/upgrading/current-edition/index.md
guides/v3.15.0/upgrading/current-edition/index.md
guides/v3.16.0/upgrading/current-edition/index.md

On https://guides.emberjs.com/release/upgrading/current-edition/#toc_implementing, **step 5** had a **bad** link. It is now **linked** to https://guides.emberjs.com/release/in-depth-topics/

Fixes broken link (#1252)

---

guides/release/getting-started/working-with-html-css-and-javascript.md

A small edit to fix grammar issue of "class's" to "classes" and then to make the two notes on the page consistently styled.
I also noticed that the notes on this page are using markdown's "quote" syntax but are appearing as normal/not styled any differently on the page. Wondering if those styles were just never edited intentionally, or if the styleguide repo also maybe needs some additional styling for notes that aren't the cta ones from the mascot? ¯\_(ツ)_/¯ either way that's something that can be addressed separately from this PR.

(maint) grammar and consistency edit

---

guides/release/getting-started/quick-start.md

Changed `Mousevent` to correct `MouseEvent`

Fix a tiny typo in getting-started/quick-start.md

---

.percy.yml
package-lock.json
package.json

This PR updates the Percy Ember SDK to the latest version. With that we're updating the underlying package that does asset discovery (`@percy/agent`). In newer versions asset discovery response caching is on by default, so we cache all network requests.
The search svg was missing in random snapshots because the test server was failing to respond when the asset discovery service would request the asset (to save). By enabling caching we can reduce the burden on the server and always have that svg in the cache (along with all other assets that load with a 200).
I've ran a number of test builds back to back locally and it looks pretty good. Curious to see how this works out over some time too 👍 
This should address #1372

deps: Upgrade Percy SDK & tweak asset discovery settings

---

.travis.yml

This will prevent forked `master` builds from resetting the Percy projects baseline.

fix:  Set `PERCY_BRANCH` for forked CI builds

---

.travis.yml

It looks like starting a bash command with `[` breaks the travis config
parser. Using their parser (https://config.travis-ci.com/explore) as a debugger
it looks like adding single quotes around the command will parse correctly
Sorry about that! Lets not merge until we know CI works :) (I assumed it didn't run due to concurrency issues or something like that) 
[edit: locks] Closes https://github.com/ember-learn/guides-source/pull/1387.

fix: Correct Travis config for forked branch parsing

---

guides/release/addons-and-dependencies/index.md

To avoid the confusion between native import and app.import function

Use app.import in docs

---

guides/release/applications/run-loop.md

1. Skip arrow syntax details, not relevant to Ember + common knowledge these days
2. Remove jQuery from runloop examples, and use 'online' event instead of 'click'.

Improve runloop examples

---

guides/versions.yml

I opted to list only the current active LTS. Should we keep every version?
Fixes https://github.com/ember-learn/guides-source/issues/1362.

update LTS versions to account for 3.16

---

guides/release/pages.yml

I found it a bit confusing that "Developer Tools" was a guide for Ember Inspector. Now that we have headings, I have added one for Developer Tools so that we can document other tools than Ember Inspector (we could have a page linking to Ember CLI, for example?) and renamed "Developer Tools" back to Ember Inspector.
Since the url was still `/ember-inspector`, I only needed to rename the text on the table of content.

Add developer tools heading and rename Ember Inspector guide

---

guides/release/upgrading/current-edition/action-on-and-fn.md

I think it would be helpful to point out this difference in the `action` and `on` modifiers. I encountered this issue when I tried to convert a component to Octane and it took a very long time to figure out the problem.

`on` does not prevent default like `action` did

---

package-lock.json
package.json

ember-cli-template-lint is deprecated and was giving this error in local dev:
```
➜  guides-source git:(master) ✗ ember serve
Cannot find configuration for extends: octane
Invalid rule configuration found: no-curly-component-invocation
Build successful (38366ms) – Serving on http://localhost:4200/
```

Use ember-template-lint instead of ember-cli-template-lint

---

guides/release/getting-started/quick-start.md

Closes https://github.com/ember-learn/guides-source/issues/633.
I went through the feedback provided by @lisaychuang and it was no longer relevant due to the section not existing anymore, the content being rewritten meanwhile, or the feedback has been incorporated somehow.

incorporate feedback from quick start review

---

guides/release/models/customizing-adapters.md
guides/v3.12.0/models/customizing-adapters.md
guides/v3.13.0/models/customizing-adapters.md
guides/v3.14.0/models/customizing-adapters.md
guides/v3.15.0/models/customizing-adapters.md
guides/v3.16.0/models/customizing-adapters.md

Fixes https://github.com/ember-learn/guides-source/issues/1411.
Removed documentation relative to the deprecated `defaultSerializer` property of Ember Data's Adapter.
I have also backported the changes to the affected versions in a separate commit, in case the team decides it should not be applied. I added that commit because I consider a bug to recommend code that will result in deprecation warnings.

Remove documentation of deprecated defaultSerializer functionality

---

guides/v3.17.0/models/customizing-adapters.md

The original PR was done before the 3.18 release so it didn't cover the 3.17 folder.

Backport removal of deprecated defaultSerializer documentation to v3.17.0 guides

---

guides/release/components/looping-through-lists.md

On Components > Looping Through Lists, a sentence reads
>  Next, lets add the component class:
"lets" here is intended to be a contraction for "let us", but that should be written "let's"
Updates to the contraction form "let's"

Correct "lets" to 'let's"

---

guides/release/components/component-state-and-actions.md

In Components > Component State and Actions, the text refers to "When the user presses the `+` button" and "When the user presses the `-` button". But the buttons are not labeled `+` and `-`, but rather `+1` and `-1`
I would expect the buttons to be referred to as "the `+1` button and the `-1` button." They are referred to as such elsewhere on this page.
Updated these references to say "the `+1` button" and "the `-1` button" to match the rest of the page.

Correct reference to counter button labels

---

README.md

Readme has a reference to "Mac OSX"
The official spelling of the OS is ["macOS"](https://en.wikipedia.org/wiki/MacOS)
Updates the spelling to "macOS"

Change spelling of Mac OSX to macOS in Readme

---

guides/release/configuring-ember/debugging.md

Fixes https://github.com/ember-learn/guides-source/issues/475.
Since we actually have a section dedicated to handling deprecations, we should link to it.

link to Handling Deprecations guide from debugging section regarding deprecations

---

.travis.yml
guides/release/routing/rendering-a-template.md

Fixes https://github.com/ember-learn/guides-source/issues/1442.

Remove templateName and renderTemplate documentation

---

guides/release/in-depth-topics/patterns-for-actions.md

Use `launchConfirmDialog` as both action function name and the reference in the template.

Fix action name in handlebars to match component

---

guides/release/configuring-ember/debugging.md

In modern apps it's required to import ember now, and it's not an import new users will be used to, so it seems logical to add it here. I also suggested to add it in app/app.js, but if there is a better place let me know and I'll update it :).

small clarification on implementing Ember.onerror

---

guides/release/components/built-in-components.md

chore: add examples for aria labels for Input

---

guides/release/components/conditional-content.md
guides/v3.15.0/components/conditional-content.md
guides/v3.16.0/components/conditional-content.md
guides/v3.17.0/components/conditional-content.md
guides/v3.18.0/components/conditional-content.md

This PR addresses and can close the issue #1237. There are 3 main changes:
1\. I reviewed the current content in `/guides/release/components/conditional-content.md` and updated it so that I can introduce the `if-else` syntax in a natural manner. Afterwards, I backported (copy-pasted) the changes to v3.15-3.18.
2\. The `Block If` and `Inline If` now have subsections called `Motivation` and `Usage`. I think making subsections helps a reader take a break (we don't overload them by showing text after text). People can also link to `Usage` for a quick access to the block and inline syntax.
3\. I created Learn More section at the end. For v3.15-3.18, I ensured that the redirect link to the API docs includes the correct version number. This addresses the issue that was brought up in #1440.
I …

Explained how to write if-else statement in templates

---

guides/release/components/block-content.md
guides/v3.15.0/components/block-content.md
guides/v3.16.0/components/block-content.md
guides/v3.17.0/components/block-content.md
guides/v3.18.0/components/block-content.md

I noticed that the titles were missing on one of the snippets halfway down the page on https://guides.emberjs.com/release/components/block-content/. It looks like the titles were there, but the tag was missing the `data-filename` attribute.

Added missing `data-filename` for code snippet titles

---

guides/v3.11.0/tutorial/hbs-helper.md
guides/v3.12.0/tutorial/hbs-helper.md
guides/v3.13.0/tutorial/hbs-helper.md
guides/v3.14.0/tutorial/hbs-helper.md

Just bringing this PR back! 🙂
This PR may be very opinionated or personal preference, but I thought the wording of this sentence is a bit awkward.
> Let's update our helper to look if a property exists in an array of communityPropertyTypes, if so, we'll return either 'Community' or 'Standalone':
I thought maybe see would sound a little better. Maybe the entire sentence needs to be restructured. Look just doesn't seem like the appropriate word here.
> Let's update our helper to see if a property exists in an array of communityPropertyTypes, if so, we'll return either 'Community' or 'Standalone':
This particular wording exist in 3.11, 3.12, 3.13, and 3.14.

Update for readability

---

guides/release/models/handling-metadata.md
guides/v3.15.0/models/handling-metadata.md
guides/v3.16.0/models/handling-metadata.md
guides/v3.17.0/models/handling-metadata.md
guides/v3.18.0/models/handling-metadata.md

The example used in handling metadata for versions 3.15-3.19 use the wrong super syntax in the `setupController` hook, this updates it from `super()` to `super.setupController()` and removes the comma on the `model()` hook

correct super syntax in the handling metadata examples 

---

guides/release/accessibility/application-considerations.md
guides/v3.10.0/reference/accessibility-guide.md
guides/v3.11.0/reference/accessibility-guide.md
guides/v3.12.0/accessibility/application-considerations.md
guides/v3.13.0/accessibility/application-considerations.md
guides/v3.14.0/accessibility/application-considerations.md
guides/v3.15.0/accessibility/application-considerations.md
guides/v3.16.0/accessibility/application-considerations.md
guides/v3.17.0/accessibility/application-considerations.md
guides/v3.18.0/accessibility/application-considerations.md
guides/v3.19.0/accessibility/application-considerations.md
guides/v3.7.0/reference/accessibility-guide.md
guides/v3.8.0/reference/accessibility-guide.md
guides/v3.9.0/reference/accessibility-guide.md
node-tests/local/external-link-checker.js

When I tested the use of `/node-tests/local/external-link-checker.js` on the `/guides/v3.18.0` folder, I found that:
- The link to the article "[How to Use Application Role](https://www.a11yproject.com/posts/2013-02-09-how-to-use-application-role/)" changed over time.
- The script incorrectly flagged `http://localhost:4200/tests` as a broken link.
I corrected the link to a11yproject and updated the script to ignore all URLs that begin with `http://localhost:4200`.

Fixed a broken link

---

guides/v3.19.0/applications/dependency-injection.md
guides/v3.19.0/applications/ember-engines.md
guides/v3.19.0/applications/index.md
guides/v3.19.0/applications/run-loop.md
guides/v3.19.0/components/built-in-components.md
guides/v3.19.0/components/conditional-content.md
guides/v3.19.0/components/helper-functions.md
guides/v3.19.0/components/looping-through-lists.md
guides/v3.19.0/configuring-ember/disabling-prototype-extensions.md
guides/v3.19.0/configuring-ember/handling-deprecations.md
guides/v3.19.0/configuring-ember/optional-features.md
guides/v3.19.0/ember-inspector/data.md
guides/v3.19.0/models/creating-updating-and-deleting-records.md
guides/v3.19.0/models/customizing-adapters.md
guides/v3.19.0/models/customizing-serializers.md
guides/v3.19.0/models/defining-models.md
guides/v3.19.0/models/finding-records.md
guides/v3.19.0/models/pushing-records-into-the-store.md
guides/v3.19.0/models/relationships.md
guides/v3.19.0/routing/asynchronous-routing.md
guides/v3.19.0/routing/controllers.md
guides/v3.19.0/routing/defining-your-routes.md
guides/v3.19.0/routing/loading-and-error-substates.md
guides/v3.19.0/routing/redirection.md
guides/v3.19.0/routing/specifying-a-routes-model.md
guides/v3.19.0/services/index.md
guides/v3.19.0/testing/test-types.md
guides/v3.19.0/testing/testing-components.md
guides/v3.19.0/upgrading/current-edition/tracked-properties.md

This PR addresses https://github.com/ember-learn/guides-source/issues/1440 for Ember `v3.19`.
I used Find All and Replace to update the URLs. Afterwards, I ran `npm run test:node-local` to check that we can visit the updated URLs.

Updated API links in guides/3.19.0

---

guides/v3.16.0/applications/dependency-injection.md
guides/v3.16.0/applications/ember-engines.md
guides/v3.16.0/applications/index.md
guides/v3.16.0/applications/run-loop.md
guides/v3.16.0/components/built-in-components.md
guides/v3.16.0/components/conditional-content.md
guides/v3.16.0/components/helper-functions.md
guides/v3.16.0/components/looping-through-lists.md
guides/v3.16.0/configuring-ember/disabling-prototype-extensions.md
guides/v3.16.0/configuring-ember/handling-deprecations.md
guides/v3.16.0/configuring-ember/optional-features.md
guides/v3.16.0/ember-inspector/data.md
guides/v3.16.0/models/creating-updating-and-deleting-records.md
guides/v3.16.0/models/customizing-adapters.md
guides/v3.16.0/models/customizing-serializers.md
guides/v3.16.0/models/defining-models.md
guides/v3.16.0/models/finding-records.md
guides/v3.16.0/models/pushing-records-into-the-store.md
guides/v3.16.0/models/relationships.md
guides/v3.16.0/routing/asynchronous-routing.md
guides/v3.16.0/routing/controllers.md
guides/v3.16.0/routing/defining-your-routes.md
guides/v3.16.0/routing/loading-and-error-substates.md
guides/v3.16.0/routing/redirection.md
guides/v3.16.0/routing/specifying-a-routes-model.md
guides/v3.16.0/services/index.md
guides/v3.16.0/testing/test-types.md
guides/v3.16.0/testing/testing-components.md

This PR addresses https://github.com/ember-learn/guides-source/issues/1440 for Ember `v3.16`.
I used Find All and Replace to update the URLs. Afterwards, I ran `npm run test:node-local` to check that we can visit the updated URLs.

Updated API links in guides/3.16.0

---

guides/v3.17.0/applications/dependency-injection.md
guides/v3.17.0/applications/ember-engines.md
guides/v3.17.0/applications/index.md
guides/v3.17.0/applications/run-loop.md
guides/v3.17.0/components/built-in-components.md
guides/v3.17.0/components/conditional-content.md
guides/v3.17.0/components/helper-functions.md
guides/v3.17.0/components/looping-through-lists.md
guides/v3.17.0/configuring-ember/disabling-prototype-extensions.md
guides/v3.17.0/configuring-ember/handling-deprecations.md
guides/v3.17.0/configuring-ember/optional-features.md
guides/v3.17.0/ember-inspector/data.md
guides/v3.17.0/models/creating-updating-and-deleting-records.md
guides/v3.17.0/models/customizing-adapters.md
guides/v3.17.0/models/customizing-serializers.md
guides/v3.17.0/models/defining-models.md
guides/v3.17.0/models/finding-records.md
guides/v3.17.0/models/pushing-records-into-the-store.md
guides/v3.17.0/models/relationships.md
guides/v3.17.0/routing/asynchronous-routing.md
guides/v3.17.0/routing/controllers.md
guides/v3.17.0/routing/defining-your-routes.md
guides/v3.17.0/routing/loading-and-error-substates.md
guides/v3.17.0/routing/redirection.md
guides/v3.17.0/routing/specifying-a-routes-model.md
guides/v3.17.0/services/index.md
guides/v3.17.0/testing/test-types.md
guides/v3.17.0/testing/testing-components.md
guides/v3.17.0/upgrading/current-edition/tracked-properties.md

This PR addresses https://github.com/ember-learn/guides-source/issues/1440 for Ember `v3.17`.
I used Find All and Replace to update the URLs. Afterwards, I ran `npm run test:node-local` to check that we can visit the updated URLs.

Updated API links in guides/3.17.0

---

guides/release/components/template-lifecycle-dom-and-modifiers.md
guides/release/configuring-ember/debugging.md

Per discussion in the [June 2020 Learning Team meeting][minutes], remove the use of `ember-ref-modifier` in favor of a custom modifier implemented using `ember-modifier`, since a custom modifier here is more idiomatic, performs better, and is more maintainable.
[minutes]: https://github.com/emberjs/core-notes/blob/259e63c328af76afff9bea4523290a57557d905d/learning-team/2020-06/2020-06-04.md
Note that this is *not* a criticism of @lifeart's original implementation of `ember-ref-modifier`: it was a very valuable early experiment with modifiers, and filled a gap when `ember-modifier` didn't even exist yet. It was precisely in experimenting with modifiers like `ref` that we figured out the patterns we now want to suggest instead!

Rewrite `ref` example using custom modifier

---

guides/release/in-depth-topics/autotracking-in-depth.md
guides/v3.15.0/in-depth-topics/autotracking-in-depth.md
guides/v3.16.0/in-depth-topics/autotracking-in-depth.md
guides/v3.17.0/in-depth-topics/autotracking-in-depth.md
guides/v3.18.0/in-depth-topics/autotracking-in-depth.md
guides/v3.19.0/in-depth-topics/autotracking-in-depth.md

Addresses https://github.com/emberjs/ember.js/issues/19030.

Document the caching of autotracked properties

---

guides/v3.15.0/components/template-lifecycle-dom-and-modifiers.md
guides/v3.15.0/configuring-ember/debugging.md
guides/v3.16.0/components/template-lifecycle-dom-and-modifiers.md
guides/v3.16.0/configuring-ember/debugging.md
guides/v3.17.0/components/template-lifecycle-dom-and-modifiers.md
guides/v3.17.0/configuring-ember/debugging.md
guides/v3.18.0/components/template-lifecycle-dom-and-modifiers.md
guides/v3.18.0/configuring-ember/debugging.md
guides/v3.19.0/components/template-lifecycle-dom-and-modifiers.md
guides/v3.19.0/configuring-ember/debugging.md

The PRs #1509 and #1510 provided a correction to `release` (`v3.20.0`). Since the correction is integral to developing an Ember Octane app, I backported the changes to `v3.15.0` to `v3.19.0`.
Cc'ed the PR authors @chriskrycho and @ghedamat to help them avoid duplicate work. 🙂

Backported updates from #1509 and #1510 to Ember Guides v3.15.0 - v3.19.0

---

guides/v3.11.0/components/index.md
guides/v3.11.0/controllers/index.md
guides/v3.11.0/models/creating-updating-and-deleting-records.md
guides/v3.11.0/models/customizing-adapters.md
guides/v3.11.0/models/customizing-serializers.md
guides/v3.11.0/models/defining-models.md
guides/v3.11.0/models/finding-records.md
guides/v3.11.0/models/pushing-records-into-the-store.md
guides/v3.11.0/models/relationships.md
guides/v3.11.0/object-model/classes-and-instances.md
guides/v3.11.0/routing/specifying-a-routes-model.md
guides/v3.11.0/tutorial/ember-data.md
guides/v3.11.0/tutorial/installing-addons.md
guides/v3.11.0/tutorial/service.md
guides/v3.11.0/tutorial/simple-component.md

This PR addresses https://github.com/ember-learn/guides-source/issues/1440 for Ember `v3.11.0`. After performing Find All and Replace, I ran `npm run test:node-local` to do a quick check that visiting a URL doesn't error.
```
Replace: https://api.emberjs.com/ember/3.11/
Replace: https://api.emberjs.com/ember/3.11/
Replace: https://api.emberjs.com/ember-data/3.11/
Replace: https://api.emberjs.com/ember-data/3.11/
```

Updated API links in guides/3.11.0

---

guides/v3.10.0/components/defining-a-component.md
guides/v3.10.0/controllers/index.md
guides/v3.10.0/models/creating-updating-and-deleting-records.md
guides/v3.10.0/models/customizing-serializers.md
guides/v3.10.0/models/finding-records.md
guides/v3.10.0/models/pushing-records-into-the-store.md
guides/v3.10.0/object-model/classes-and-instances.md
guides/v3.10.0/templates/input-helpers.md
guides/v3.10.0/tutorial/service.md
guides/v3.10.0/tutorial/simple-component.md
guides/v3.11.0/models/creating-updating-and-deleting-records.md
guides/v3.11.0/models/finding-records.md
guides/v3.11.0/templates/input-helpers.md
guides/v3.12.0/models/creating-updating-and-deleting-records.md
guides/v3.13.0/models/creating-updating-and-deleting-records.md
guides/v3.14.0/models/creating-updating-and-deleting-records.md
guides/v3.8.0/models/creating-updating-and-deleting-records.md
guides/v3.8.0/templates/input-helpers.md
guides/v3.9.0/models/creating-updating-and-deleting-records.md
guides/v3.9.0/templates/input-helpers.md

This PR addresses https://github.com/ember-learn/guides-source/issues/1440 for Ember `v3.10.0`. After performing Find All and Replace, I ran `npm run test:node-local` to do a quick check that visiting a URL doesn't error.
Because relatively few links changed, I was able to manually visit each to ensure that we redirected the user to the correct page.
I recommend reviewing commits one by one.
```
Replace: https://api.emberjs.com/ember/3.10/
Replace: https://api.emberjs.com/ember/3.10/
Replace: https://api.emberjs.com/ember-data/3.10/
Replace: …
```

Updated API links in guides/3.10.0

---

guides/v3.9.0/components/defining-a-component.md
guides/v3.9.0/controllers/index.md
guides/v3.9.0/models/creating-updating-and-deleting-records.md
guides/v3.9.0/models/customizing-serializers.md
guides/v3.9.0/models/finding-records.md
guides/v3.9.0/models/pushing-records-into-the-store.md
guides/v3.9.0/object-model/classes-and-instances.md
guides/v3.9.0/tutorial/service.md
guides/v3.9.0/tutorial/simple-component.md

This PR addresses https://github.com/ember-learn/guides-source/issues/1440 for Ember `v3.9.0`. After performing Find All and Replace, I ran `npm run test:node-local` to do a quick check that visiting a URL doesn't error.
Because relatively few links changed, I was able to manually visit each to ensure that we redirected the user to the correct page.
I recommend reviewing commits one by one.
```
Replace: https://api.emberjs.com/ember/3.9/
Replace: https://api.emberjs.com/ember/3.9/
Replace: https://api.emberjs.com/ember-data/3.9/
Replace: https://api.emberjs.com/ember-data/3.9/ …
```

Updated API links in guides/3.9.0

---

guides/v3.8.0/components/defining-a-component.md
guides/v3.8.0/controllers/index.md
guides/v3.8.0/models/creating-updating-and-deleting-records.md
guides/v3.8.0/models/customizing-serializers.md
guides/v3.8.0/models/finding-records.md
guides/v3.8.0/models/pushing-records-into-the-store.md
guides/v3.8.0/object-model/classes-and-instances.md
guides/v3.8.0/testing/testing-models.md
guides/v3.8.0/tutorial/service.md
guides/v3.8.0/tutorial/simple-component.md

This PR addresses https://github.com/ember-learn/guides-source/issues/1440 for Ember `v3.8.0`. After performing Find All and Replace, I ran `npm run test:node-local` to do a quick check that visiting a URL doesn't error.
Because relatively few links changed, I was able to manually visit each to ensure that we redirected the user to the correct page.
I recommend reviewing commits one by one.
```
Replace: https://api.emberjs.com/ember/3.8/
Replace: https://api.emberjs.com/ember/3.8/
Replace: https://api.emberjs.com/ember-data/3.8/
Replace: https://api.emberjs.com/ember-data/3.8/ …
```

Updated API links in guides/3.8.0

---

guides/v3.6.0/controllers/index.md
guides/v3.6.0/object-model/classes-and-instances.md
guides/v3.6.0/templates/writing-helpers.md
guides/v3.6.0/tutorial/service.md

This PR addresses #1440 for Ember `v3.6.0`.
I recommend reviewing commits one by one.
```
Replace: https://api.emberjs.com/ember/3.6/
Replace: https://api.emberjs.com/ember/3.6/
Replace: https://api.emberjs.com/ember-data/3.6/
Replace: https://api.emberjs.com/ember-data/3.6/
```

Updated Ember API links for 3.6.0

---

guides/release/accessibility/components.md
guides/release/components/built-in-components.md
guides/release/components/helper-functions.md
guides/release/configuring-ember/optional-features.md
guides/release/models/creating-updating-and-deleting-records.md
guides/release/models/customizing-serializers.md
guides/release/models/index.md
guides/release/testing/unit-testing-basics.md

https://github.com/ember-learn/guides-source/issues/1480
TL;DR Replacing `firstName` and `lastName` example code with `givenName` or `familyName`, or `title` and `name`, or just simply `name`, or something else entirely for i18n/W3C/respect concerns.
I don't feel this needs to go back prior to `/release` but I'm open to a suggested amount of backporting.
Open to suggested alternatives for these changes as well.

Replace (some) of First & Last Name variable example references

---

guides/release/testing/unit-testing-basics.md
guides/v3.15.0/testing/unit-testing-basics.md
guides/v3.16.0/testing/unit-testing-basics.md
guides/v3.17.0/testing/unit-testing-basics.md
guides/v3.18.0/testing/unit-testing-basics.md
guides/v3.19.0/testing/unit-testing-basics.md
guides/v3.20.0/testing/unit-testing-basics.md

As pointed out by @ijlee2 in #1530 this assertion is invalid because...
> ...`someThing.employees[0]` and `person` are both class instances...
```js
assert.equal(someThing.employees[0], person);
```

Removed incorrect assertion

---

guides/release/applications/run-loop.md
guides/release/configuring-ember/disabling-prototype-extensions.md
guides/release/getting-started/working-with-html-css-and-javascript.md
guides/release/in-depth-topics/autotracking-in-depth.md
guides/release/upgrading/current-edition/tracked-properties.md

https://github.com/ember-learn/guides-source/issues/1480
Prior batch: https://github.com/ember-learn/guides-source/pull/1530
TL;DR Replacing `firstName` and `lastName` example code with `title` and `name`, or just simply `name`, or something else entirely for i18n/W3C/respect concerns.
I don't feel this needs to go back prior to `/release` but I'm open to a suggested amount of backporting.
Open to suggested alternatives for these changes as well.

Replace (some) of First & Last Name variable example references (Batch 2)

---

.github/FUNDING.yml

People can sponsor Ember.js through [GitHub](https://github.com/sponsors/emberjs) and [OpenCollective](https://opencollective.com/emberjs). Let's make the links visible in the `guides-source` repo.
- https://docs.github.com/free-pro-team@latest/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository#about-funding-files

Added GitHub and OpenCollective as sponsorship methods

---

.github/FUNDING.yml

Now that the Sponsor button is [added at the `ember-learn` organization level](https://github.com/ember-learn/.github/pull/1), we can revert #1544 to remove the repo-specific `.github/FUNDING.yml` file.

Revert "Added GitHub and OpenCollective as sponsorship methods"

---

guides/release/in-depth-topics/autotracking-in-depth.md
guides/v3.15.0/in-depth-topics/autotracking-in-depth.md
guides/v3.16.0/in-depth-topics/autotracking-in-depth.md
guides/v3.17.0/in-depth-topics/autotracking-in-depth.md
guides/v3.18.0/in-depth-topics/autotracking-in-depth.md
guides/v3.19.0/in-depth-topics/autotracking-in-depth.md
guides/v3.20.0/in-depth-topics/autotracking-in-depth.md

Fixes #1551 
<pre>The cache API was released in Ember 3.22. If you want to leverage this API between versions 3.13 and 3.21, you can install [ember-cache-primitive-polyfill](https://github.com/ember-polyfills/ember-cache-primitive-polyfill) to your project.</pre>
- guides/v3.15.0/in-depth-topics/autotracking-in-depth.md
- guides/v3.16.0/in-depth-topics/autotracking-in-depth.md
- guides/v3.17.0/in-depth-topics/autotracking-in-depth.md
- guides/v3.18.0/in-depth-topics/autotracking-in-depth.md
- guides/v3.19.0/in-depth-topics/autotracking-in-depth.md
- guides/v3.20.0/in-depth-topics/autotracking-in-depth.md
- guides/release/in-depth-topics/autotracking-in-depth.md

Document how to use caching primitives in Ember 3.15 - 3.21

---

guides/release/in-depth-topics/native-classes-in-depth.md
guides/release/models/defining-models.md
guides/release/upgrading/current-edition/glimmer-components.md
guides/release/upgrading/current-edition/native-classes.md

https://github.com/ember-learn/guides-source/issues/1480
Prior batch: https://github.com/ember-learn/guides-source/pull/1537
_This is the last batch!_
TL;DR Replacing `firstName` and `lastName` example code with `title` and `name`, or just simply `name`, or something else entirely for i18n/W3C/respect concerns.
I don't feel this needs to go back prior to `/release` but I'm open to a suggested amount of backporting.
Open to suggested alternatives for these changes as well.

Replace (some) of First & Last Name variable example references (Batch 3)

---

.local.dic
guides/release/components/built-in-components.md

This PR addresses and can close issue #1543 . In particular, in the Ember Learning Team's `Input component plans` document, this PR completes 3 action items:
I read everything in [Built-In Components](https://guides.emberjs.com/release/components/built-in-components/) to figure out how to update each subsection and its examples, so that the updated page will be coherent as a whole.
I also created a new Ember v3.21.1 app. I copy-pasted the existing code samples to figure out what worked and what didn't. The updated code samples should work when a developer copy-pastes them to a new app (assuming v3.21).
I recommend reviewing commits one by one. Each commit looks at one subsection in `Built-In Components`.
In meeting, @chancancode, @jenweber, @locks, and I weren't sure whether, with …

Updated Built-In Components page to clarify how to use <Input> component

---

guides/release/routing/specifying-a-routes-model.md

- Align file name and class name
- Use singular noun for `store.findAll`

Fix typos in specifying-a-routes-model.md

---

guides/release/models/index.md
guides/release/routing/specifying-a-routes-model.md
guides/v3.15.0/models/index.md
guides/v3.15.0/routing/specifying-a-routes-model.md
guides/v3.16.0/models/index.md
guides/v3.16.0/routing/specifying-a-routes-model.md
guides/v3.17.0/models/index.md
guides/v3.17.0/routing/specifying-a-routes-model.md
guides/v3.18.0/models/index.md
guides/v3.18.0/routing/specifying-a-routes-model.md
guides/v3.19.0/models/index.md
guides/v3.19.0/routing/specifying-a-routes-model.md
guides/v3.20.0/models/index.md
guides/v3.20.0/routing/specifying-a-routes-model.md

Through a [Discord conversation](https://discordapp.com/channels/480462759797063690/483601670685720591/759024759093592095), I realized that we didn't explain well when a developer needs to inject the Ember Data store service:
> Developer: Hello all. Just a quick Q: I’m using this.store in my model() without injecting it as a service and it’s all working as expected. Am I missing something or am I just lucky? (I’ve just seen that the docs inject as a service)
I also noticed that the `Zoey says` has a Markdown typo (we unfortunately have to manually provide a `<code>` tag).
I recommend reviewing commits one by one. Each commit makes the same type of change across different versions, starting with Ember 3.15 (Octane).
- https://guides.emberjs.com/release/routing/specifying-a-routes-model/#toc …

Updated how we describe injecting Ember Data store

---

guides/release/configuring-ember/debugging.md

This should address #1574. Originally I had written a blurb on the features of ember inspector and included the install links until I realized that we had a whole section dedicated to it. So I slimmed down the description and included a link to the existing guide.
I felt like the Ember inspector was important enough to be included at the top of the debugging section. IMO, its the equivalent of "is your computer turned on?"

Adding Ember Inspector link to debugging.md

---

node-tests/local/external-link-checker.js

While opening https://github.com/ember-learn/guides-source/pull/1582 I ran through all the link tests listed in README.md. There was a single test failure when I ran `npm run test:node-local-exclude-api-urls`
Navigating to https://www.ember-cli-mirage.com/docs/testing/acceptance-tests does result in a 404. Then the router kicks in and puts the path of the request onto a query parameter.
I have changed the URL to the query param'd URL, so that the curl receives a 200 from that link.
However, I don't know how future-proof that link is (if they ever change the router). Another option we have is to adding that link to the `doNotCheckList` in `external-link-checker.js`
```js
const doNotCheckList = [
'http://localhost:4200',
'https://codepen.io/melsumner/live/ZJeYoP', // codepen does not play …
```

Update the url of ember-cli-mirage testing docs to avoid test failure

---

guides/v3.15.0/routing/specifying-a-routes-model.md
guides/v3.16.0/routing/specifying-a-routes-model.md
guides/v3.17.0/routing/specifying-a-routes-model.md
guides/v3.18.0/routing/specifying-a-routes-model.md
guides/v3.19.0/routing/specifying-a-routes-model.md
guides/v3.20.0/routing/specifying-a-routes-model.md

- Changes taken from https://github.com/ember-learn/guides-source/pull/1571/files
- Changed specifying a route's model from v3.15.0 to v.3.20.0
- Closes #1572

Backport changes to Specifying a Route's Model

---

package.json
scripts/create-new-minor-version
scripts/update-version-links

Currently using `npm run release:guides:minor` to create a new release copies `guides/release` to a its version number (eg. `guides/v3.22.0`), but there is no automated way to update the version numbers in all links pointing to its guides or API links.
See issue #1440 and its https://github.com/ember-learn/guides-source/issues/1440#issuecomment-666800602 to see how much of a chore this convoluted process is.
This PR attempts to:
* Provide a CLI script that can be used on old releases and update its version numbers
* Hook into the current `release:guides:minor` script and automate the process for future releases
---
The new npm script `release:guides:links` syntax looks like this:
```
npm run release:guides:links <guides-path> <release-number> -- <options...>
```
A good example for this …

New script to update version links using the correct version number instead of release

---

guides/v3.1.0/object-model/classes-and-instances.md
guides/v3.1.0/templates/writing-helpers.md
guides/v3.1.0/tutorial/service.md
guides/v3.2.0/object-model/classes-and-instances.md
guides/v3.2.0/templates/writing-helpers.md
guides/v3.2.0/tutorial/service.md
guides/v3.3.0/templates/writing-helpers.md
guides/v3.4.0/controllers/index.md
guides/v3.4.0/object-model/classes-and-instances.md
guides/v3.4.0/templates/writing-helpers.md
guides/v3.5.0/controllers/index.md
guides/v3.5.0/object-model/classes-and-instances.md
guides/v3.5.0/templates/writing-helpers.md

This PR addresses #1440 for Ember `v3.1.0` to `v3.5.0`.
1. Ran the script `npm run release:guides:links <guides-path> <version>`
2. Manually checked updated links
3. Ran `npm run test:node-local` to check all external links automatically

Updated API links in guides - phase 3

---

guides/release/code-editors/index.md

I think we should show both Ember Language Server and Unstable Language Server in this list. This is a brand-new page for the Guides, just merged today, and this is a followup PR.
@lifeart are there any other differentiators to mention here?

Add Unstable Language Server to IDE plugins

---

guides/v3.15.0/in-depth-topics/native-classes-in-depth.md
guides/v3.16.0/in-depth-topics/native-classes-in-depth.md
guides/v3.17.0/in-depth-topics/native-classes-in-depth.md
guides/v3.18.0/in-depth-topics/native-classes-in-depth.md
guides/v3.19.0/in-depth-topics/native-classes-in-depth.md
guides/v3.20.0/in-depth-topics/native-classes-in-depth.md
guides/v3.21.0/in-depth-topics/native-classes-in-depth.md

Following on from #1613 (@ijlee2):
Sorry about the commit history mess! I did the other PRs on my iPad with the "Edit page" link at the top of the docs.
I didn't realise there were different directories with the different versions like this. I'll know for next time :)

native-classes-in-depth.md edits #1613 and #1614 for more guide versions

---

guides/release/upgrading/current-edition/tracked-properties.md
guides/v3.15.0/upgrading/current-edition/tracked-properties.md
guides/v3.16.0/upgrading/current-edition/tracked-properties.md
guides/v3.17.0/upgrading/current-edition/tracked-properties.md
guides/v3.18.0/upgrading/current-edition/tracked-properties.md
guides/v3.19.0/upgrading/current-edition/tracked-properties.md
guides/v3.20.0/upgrading/current-edition/tracked-properties.md
guides/v3.21.0/upgrading/current-edition/tracked-properties.md

https://guides.emberjs.com/release/upgrading/current-edition/tracked-properties/#toc_backwards-compatibility
The example describes using get to read a property that isn't tracked, and how that achieves autotracking. 
The trouble is, the example loads the properties into locals then doesn't use them. That confused me: was the aim to side-effect the property (adding tracking to it), or was it to load tracked values with `get` and calculate the ratio with them?
I'm not sure if those semantics matter to people upgrading apps, but I was distracted by the variables being set then not used. It looks like a copy-paste leftover rather than a deliberate part of the example.
If it was deliberate, I'd suggest something like this instead: 
```
get aspectRatio() {
get(this, 'width');
get(this, …
```

upgrading / tracked properties / backwards-compatibility: use the locals

---

guides/release/getting-started/quick-start.md

fixes issue #1599 -does this wording look okay? please review.

Issue 1599 - add --lang option to guide 

---

guides/release/configuring-ember/optional-features.md

Updates the jquery-integration guide to match the updates proposed in
the [deprecation RFC](https://github.com/emberjs/rfcs/blob/master/text/0705-deprecate-jquery-optional-feature.md).

Update jquery-integration optional feature guide

---

guides/release/components/block-content.md
guides/v3.15.0/components/block-content.md
guides/v3.16.0/components/block-content.md
guides/v3.17.0/components/block-content.md
guides/v3.18.0/components/block-content.md
guides/v3.19.0/components/block-content.md
guides/v3.20.0/components/block-content.md
guides/v3.21.0/components/block-content.md
guides/v3.22.0/components/block-content.md
guides/v3.23.0/components/block-content.md

- Fixed some incorrectly closed `<h2>` tags in block-content.md.
- Also made the same corrections in the previous versions of the
docs (v3.15.0-v3.23.0).

[Docs] Correct some closing HTML tags

---

guides/release/applications/dependency-injection.md
guides/v3.15.0/applications/dependency-injection.md
guides/v3.16.0/applications/dependency-injection.md
guides/v3.17.0/applications/dependency-injection.md
guides/v3.18.0/applications/dependency-injection.md
guides/v3.19.0/applications/dependency-injection.md
guides/v3.20.0/applications/dependency-injection.md
guides/v3.21.0/applications/dependency-injection.md
guides/v3.22.0/applications/dependency-injection.md
guides/v3.23.0/applications/dependency-injection.md
guides/v3.24.0/applications/dependency-injection.md

I guess this will need work before it's usable, if it's good at all, but I found this difficult to learn & thought a PR would be more constructive than an issue?
The DI registration syntax can be intimidating. It's fairly
straightforward, but there's a lot to read and no brief summary
of the expected or default syntax from an ember-cli app using the
default file structure. Subdirectories are the main issue. There are
no /s in the examples.
This adds a subheading and an example with a subdirectory looking up a
controller, as might be used in a controller unit test.

DI: summarise name and subdirectory format

---

guides/release/components/block-content.md
guides/v3.15.0/components/block-content.md
guides/v3.16.0/components/block-content.md
guides/v3.17.0/components/block-content.md
guides/v3.18.0/components/block-content.md
guides/v3.19.0/components/block-content.md
guides/v3.20.0/components/block-content.md
guides/v3.21.0/components/block-content.md
guides/v3.22.0/components/block-content.md
guides/v3.23.0/components/block-content.md
guides/v3.24.0/components/block-content.md

This adds the missing `alt` attribute (needed for screen readers and accessibility).

Add empty alternate text and role presentation to blog logo example

---

app/index.html

Resolves: https://github.com/ember-learn/guides-source/issues/1621
Related to: https://github.com/ember-learn/ember-website/pull/804

Fix meta image

---

app/index.html

We discussed https://github.com/ember-learn/guides-source/pull/1647 in the Learning meeting and the plan was to delete the descriptions from the index.html because they need to be dynamic based on each route in the app. 
This just removes the static description that crept in 👍

Remove static meta description

---

guides/v3.10.0/templates/input-helpers.md
guides/v3.11.0/templates/input-helpers.md
guides/v3.12.0/templates/input-helpers.md
guides/v3.13.0/templates/input-helpers.md
guides/v3.14.0/templates/input-components.md
guides/v3.7.0/templates/input-helpers.md
guides/v3.8.0/templates/input-helpers.md
guides/v3.9.0/templates/input-helpers.md

@ijlee2 Please review my first PR for the issue https://github.com/ember-learn/guides-source/issues/1016
Let me know if you have any feedback! 
1) List of changes done to the Input Components page (v3.14)
- Remove the @name="isAdmin" in https://guides.emberjs.com/v3.14.0/templates/input-components/#toc_checkboxes. (This better matches the new code example in v3.15.)
- Update the code <Input @type="text" @keyPress={{action "updateName"}} /> to:
`<Input @id="admin-checkbox" @type="checkbox" @checked={{this.isAdmin}} @input={{this.validateRole}} />`
2) List of changes done to the Input Helpers page (v3.7 - v3.9)
-  Update the code {{input type="checkbox" keyPress=(action "updateName")}} to:
`{{input type="checkbox" name="isAdmin" checked=this.isAdmin input=(action "validateRole")}}`
3) List …

changes to code examples of Input Components page (#1016)

---

guides/release/contributing/adding-new-features.md
guides/release/contributing/index.md
guides/release/pages.yml

This other PR had a bunch of merge conflicts since we moved some files around and also edited those files, as part of several contributors' workshop PRs: https://github.com/ember-learn/guides-source/pull/1665
This PR here squashes the commits from #1665, rebases them on `master`, and fixes the merge conflicts.
The new content was already reviewed, so I'll merge this as soon as I confirm that it all looks good and I didn't make any rebasing mistakes.

Continued - Create a short Contributing Overview guide

---

guides/versions.yml

Since [March 17, 2021](https://emberjs.com/releases/lts), 3.16 LTS is no longer supported.

Removed 3.16 from currently supported LTS versions

---

guides/release/components/block-content.md

I added a simple example, but did so in a way that acknowledges named blocks and the "default" block. I think that named blocks are a valuable feature, and acknowledging the little bit of complexity can make it all seem a little less magical when the reader encounters named blocks later.
closes #1659

Add default block content example at the top of the section

---

guides/release/routing/loading-and-error-substates.md

The class name and filename are not coherent.

Wrong class name in loading-and-error-substates

---

guides/release/testing/testing-application.md

I just ran into this today. trying to test a h1
```
document.querySelector('h1)
```
Is returning my app name... The code should be updated to use the helpers.

Use test selectors instead of DOM selectors

---

guides/release/upgrading/current-edition/native-classes.md

Some code blocks on the `native-classes` page are nested inside an unordered list.
For the code block indentation to work correctly, an indentation of `4` spaces is needed for every level of the list - there are currently `2`, which is causing the first degree of indentation in each code block to be lost (example shown below):
Live example: [as-is](https://guides.emberjs.com/release/upgrading/current-edition/native-classes/#toc_instantiation) vs [proposed](https://deploy-preview-1703--ember-guides.netlify.app/release/upgrading/current-edition/native-classes/#toc_instantiation).

Fix nested code block indentation

---

guides/release/testing/testing-components.md

Adapt and fix code for Glimmer components (missing `@tracked`, `this.set(...)` instead of `this.xx = ...`, `this.xx` instead of `@xx` etc).

Adapt and fix code for Glimmer components

---

guides/v3.15.0/upgrading/current-edition/native-classes.md
guides/v3.16.0/upgrading/current-edition/native-classes.md
guides/v3.17.0/upgrading/current-edition/native-classes.md
guides/v3.18.0/upgrading/current-edition/native-classes.md
guides/v3.19.0/upgrading/current-edition/native-classes.md
guides/v3.20.0/upgrading/current-edition/native-classes.md
guides/v3.21.0/upgrading/current-edition/native-classes.md
guides/v3.22.0/upgrading/current-edition/native-classes.md
guides/v3.23.0/upgrading/current-edition/native-classes.md
guides/v3.24.0/upgrading/current-edition/native-classes.md
guides/v3.25.0/upgrading/current-edition/native-classes.md
guides/v3.26.0/upgrading/current-edition/native-classes.md

A follow-up to https://github.com/ember-learn/guides-source/pull/1703, backporting the change made in `current-edition` to `v3.15`, ..., `v3.26`.
> Some code blocks on the `native-classes` page are nested inside an unordered list.
> For the code block indentation to work correctly, an indentation of `4` spaces is needed for every level of the list - there are currently `2`, which is causing the first degree of indentation in each code block to be lost (example shown below):

Backport code block indentation

---

guides/release/configuring-ember/debugging.md

I'm not entirely sure that this is the right place to put it, but current wording is pretty vague.
Do I need to add it to my application code? To my tests? In `beforeEach` of my tests?
Also current version makes an assumption that the user knows that they need to import `Ember`.

Make backburner docs more explicit

---

.local.dic
guides/release/components/helper-functions.md
guides/v3.20.0/components/helper-functions.md
guides/v3.21.0/components/helper-functions.md
guides/v3.22.0/components/helper-functions.md
guides/v3.23.0/components/helper-functions.md
guides/v3.24.0/components/helper-functions.md
guides/v3.25.0/components/helper-functions.md
guides/v3.26.0/components/helper-functions.md

This PR looks to resolve #1492.
We are adding an example and documentation to the `in-element` helper on the [Built in helper](https://guides.emberjs.com/release/components/helper-functions/#toc_built-in-helpers) section. I added the same into the version of the guides that have the `in-element` helper.

Document in-element in the Guides (#1492)

---

guides/release/upgrading/current-edition/glimmer-components.md

* Template-only components don't inherit from `@glimmer/component`.
* Also removed the "pure function" verbiage which felt a bit jargon-y without adding much information, and isn't consistent with how we teach/describe components in the rest of the guides.

Template-only components fixes

---

guides/release/in-depth-topics/native-classes-in-depth.md

I have pointed the link to [this location](https://api.emberjs.com/ember/3.27/modules/@ember%2Fobject#functions). 
Should we remove the words "later on" as mentioned in the issue description? @jenweber

Converting decorator text as link (#1694)

---

package-lock.json

This fixes the issue that people might be facing if they have updated watchman on their machines where the new date-based watchman version isn't considered valid for ember-cli
This will also fix the "too many open files" problem for the same users 👍

fix watchman issue

---

guides/release/getting-started/working-with-html-css-and-javascript.md

There are 2 lingering places outside the upgrade guides where we talk about classic components/classes.
For new developer experience, I recommend that we keep them around, but with some rewording. They are all over stack overflow.

Reword some "Classic" references for Ember 4

---

scripts/update-search-index

The script was creating too many indices for algolia.
We discovered that a tmp dir was holding all the old
versions. You can reproduce this bug by deleting dist,
deleting some versions, and running ember build.
The resulting dist had all the versions, including
those that were deleted.
Co-authored by @mansona

Remove tmp  during search index creation

---

guides/release/upgrading/current-edition/glimmer-components.md

I'm not sure if the "ember-render-modifiers" was used intentionally here(at least the github repo has this name). However, it encouraged me to run `ember install ember-render-modifiers`, which has failed cause a real package name is the "@ember/render-modifiers".

ember-render-modifiers => @ember/render-modifiers

---

guides/release/upgrading/current-edition/glimmer-components.md
guides/v3.15.0/upgrading/current-edition/glimmer-components.md
guides/v3.16.0/upgrading/current-edition/glimmer-components.md
guides/v3.17.0/upgrading/current-edition/glimmer-components.md
guides/v3.18.0/upgrading/current-edition/glimmer-components.md
guides/v3.19.0/upgrading/current-edition/glimmer-components.md
guides/v3.20.0/upgrading/current-edition/glimmer-components.md
guides/v3.21.0/upgrading/current-edition/glimmer-components.md
guides/v3.22.0/upgrading/current-edition/glimmer-components.md
guides/v3.23.0/upgrading/current-edition/glimmer-components.md
guides/v3.24.0/upgrading/current-edition/glimmer-components.md
guides/v3.25.0/upgrading/current-edition/glimmer-components.md
guides/v3.26.0/upgrading/current-edition/glimmer-components.md
guides/v3.27.0/upgrading/current-edition/glimmer-components.md

[This section](https://guides.emberjs.com/release/upgrading/current-edition/glimmer-components/#toc_arguments) of the guides provides an example of how to use getters for default Glimmer component args, but in the example the original immutable args are used to compute `aspectRatio` rather than the getters that provide default values. This could be confusing because it could imply that the getters somehow provide defaults to the args when accessed via `this.args`. Instead, IMHO, the arg-consuming getter (`aspectRatio`) should demonstrate using the getters rather than the original args. This PR makes that change for all versions that include this example (all Octane versions).

Fix default glimmer args example

---

guides/release/components/template-lifecycle-dom-and-modifiers.md

The previous version of this example was lacking the imports and used a bare class instead of one which `extends Component`, and also did not include the `@action` binding, so would simply not have worked.

Fix backing class in Template Lifecycle, DOM, and Modifiers

---

guides/release/components/helper-functions.md

This PR is motivated by a question that was surfaced by [this issue](https://github.com/emberjs/ember.js/issues/19519) in the [emberjs repo ](https://github.com/emberjs/ember.js).  
The `get` helper use can be extended to objects with string or numeric keys, so arrays can also make use of the helper. This PR updates the docs to have examples of all of these use cases and have a more generic definition of what the `get` helper can do.

Update documentation for get helper

---

guides/release/applications/dependency-injection.md
guides/release/in-depth-topics/patterns-for-actions.md
guides/release/models/customizing-adapters.md
guides/release/models/handling-metadata.md
guides/release/models/pushing-records-into-the-store.md
guides/release/models/relationships.md
guides/release/routing/asynchronous-routing.md
guides/release/routing/defining-your-routes.md
guides/release/routing/loading-and-error-substates.md
guides/release/routing/preventing-and-retrying-transitions.md
guides/release/routing/query-params.md
guides/release/routing/redirection.md
guides/release/routing/specifying-a-routes-model.md
guides/release/services/index.md
guides/release/testing/testing-components.md
guides/release/upgrading/current-edition/native-classes.md

Updated to be inline with [RFC 752](https://emberjs.github.io/rfcs/0752-inject-service.html).

Use service named import instead of inject

---

guides/release/code-editors/index.md

This extension isn't needed anymore to use Prettier with Templates anymore.
The recommendation now (at least from me) is to use Ember Template Lint with the [Prettier Plugin](https://github.com/ember-template-lint/ember-template-lint-plugin-prettier)
To auto fix on save in VSCode it is possible to use the `emeraldwalk.runonsave` extension with these settings:
```
// Settings for `RunOnSave` extension
"emeraldwalk.runonsave": {
"commands": [
{
// For every `.hbs` run the template linter in fix mode
"match": "\\.hbs$",
"cmd": "yarn run ember-template-lint ${file} --fix"
}
]
},
```

Remove Prettier for Handlebars recommendation

---

guides/release/addons-and-dependencies/index.md

Since the [Bower RFC implementation](https://github.com/ember-cli/ember-cli/pull/9707) has been merged (I assume it will be part of the upcoming `v4.2` release), I think we can start removing references to Bower from the guides?

Remove references to Bower

---

scripts/update-search-index

This fixes a bug in search index deploy scripts.
We pre-build some older versions of the guides to make our
builds faster. Our search index scripts were picking up on
these, making everything slow and overwriting a lot of our
indexes every time we deployed. Now, we delete
those pre-built versions before running the index.
#1777

Bugfix - search index script omits prebuilt guides

---

guides/release/configuring-ember/disabling-prototype-extensions.md

Ember v4 removed the `String` and `Function` prototype extensions, so the docs about both are now confusing and misleading. Remove those, andupdate the guidance for `Array` prototype extensions to describe the native `Array` and `TrackedArray` alternatives.

Update disabling prototype extensions guide for v4

---

guides/release/code-editors/index.md

`Ember Language Server` is not under active maintaining, but `Unstable Ember Language Server` is. 
`UELS` includes all `ELS` features and has a lot [more](https://github.com/lifeart/ember-language-server#features).
Right now `UELS` is the main `VSCode` extension for Ember developers.
If `UELS` will be in the first place, new Ember developers will use it and have more comfortable experience.

Remove Ember Language Server from the list of Visual Studio Code's extensions

---

guides/release/models/index.md

The implicit injection has been deprecated, so the callout is factually wrong.
After we land on the final wording we want, this should be backported to at least 4.0 (taking care to make sure `import { service }` is supported) and maybe even down to whenever the implicit injection deprecation was released?

Fix Ember Data call out regarding store

---

guides/release/upgrading/current-edition/tracked-properties.md
guides/v3.15.0/upgrading/current-edition/tracked-properties.md
guides/v3.16.0/upgrading/current-edition/tracked-properties.md
guides/v3.17.0/upgrading/current-edition/tracked-properties.md
guides/v3.18.0/upgrading/current-edition/tracked-properties.md
guides/v3.19.0/upgrading/current-edition/tracked-properties.md
guides/v3.20.0/upgrading/current-edition/tracked-properties.md
guides/v3.21.0/upgrading/current-edition/tracked-properties.md
guides/v3.22.0/upgrading/current-edition/tracked-properties.md
guides/v3.23.0/upgrading/current-edition/tracked-properties.md
guides/v3.24.0/upgrading/current-edition/tracked-properties.md
guides/v3.25.0/upgrading/current-edition/tracked-properties.md
guides/v3.26.0/upgrading/current-edition/tracked-properties.md
guides/v3.27.0/upgrading/current-edition/tracked-properties.md
guides/v3.28.0/upgrading/current-edition/tracked-properties.md
guides/v4.0.0/upgrading/current-edition/tracked-properties.md

I have pointed developers at these docs and they had some uncertainty over where `get` and `set` come from. I've added the `get` and `set` imports to the examples for clarity.

add get and set imports to tracked backwards compat examples

---

guides/release/upgrading/index.md
guides/v3.15.0/upgrading/index.md
guides/v3.16.0/upgrading/index.md
guides/v3.17.0/upgrading/index.md
guides/v3.18.0/upgrading/index.md
guides/v3.19.0/upgrading/index.md
guides/v3.20.0/upgrading/index.md
guides/v3.21.0/upgrading/index.md
guides/v3.22.0/upgrading/index.md
guides/v3.23.0/upgrading/index.md
guides/v3.24.0/upgrading/index.md
guides/v3.25.0/upgrading/index.md
guides/v3.26.0/upgrading/index.md
guides/v3.27.0/upgrading/index.md
guides/v3.28.0/upgrading/index.md
guides/v4.0.0/upgrading/index.md
guides/v4.1.0/upgrading/index.md
guides/v4.2.0/upgrading/index.md

Throughout all of the guides since v3.15.0, we have a broken link to the
"/ember-inspector/deprecations" page. Let's go through and fix this
retroactively so consumers of the guides can find the content that they're
looking for a little bit easier.

guides: fix "tools for deprecations" links

---

guides/release/code-editors/index.md

"Unstable Ember Language Server" was recently renamed to "[Stable Ember Language Server](https://marketplace.visualstudio.com/items?itemName=lifeart.vscode-ember-unstable)" so just updating the content to reflect that

Update name of VS Code extension

---

guides/release/getting-started/quick-start.md

Needs to be in /public, instead of the root folder to work.

Fix for _redirect file location in quick start docs

---

guides/release/components/introducing-components.md
guides/v4.2.0/components/introducing-components.md

A very minor issue I noticed while reading https://guides.emberjs.com/release/components/introducing-components/
Previously the + appeared on the /form line - it should appear on the NewMessageInput.

guides: Fix diff lines for adding NewMessageInput

---

guides/release/models/creating-updating-and-deleting-records.md
guides/release/routing/redirection.md

Closes #1754
We mostly replaced the outdated uses of transitionToRoute/replaceWithRoute, but there were a couple links hanging around. The code samples already use the service, like they are supposed to.
Only 1 reviewer is needed, from any team member.

Remove some outdated route method references

---

guides/release/configuring-ember/specifying-url-type.md

The current new CLI output (starting with ember-cli 4.1.1 it appears) writes the locationType as 'history' now, instead of 'auto'.

Update specifying-url-type.md with new default

---

guides/v4.5.0/getting-started/index.md

In maybe the most pedantic correction ever, add a period to the features list on the one bullet point missing it, for stylistic consistency in the guides.

Add missing period to features list

---

.local.dic
guides/release/code-editors/index.md

Prettier for Handlebars is deprecated in favor of using Prettier for Handlebars natively using Prettier itself.

Replacing from "Prettier for Handlebars" to "Prettier"

---

guides/release/contributing/adding-new-features.md

Designate rfcs.emberjs.com as the source of truth for RFCs

---

guides/release/accessibility/application-considerations.md

`ember-gestures` and its dependency, `ember-hammertime`, are no longer maintained and do not function at all on recent versions of Ember.
Refs:
- https://github.com/html-next/ember-gestures/issues/139
- https://github.com/html-next/ember-hammertime/issues/103

Remove `ember-gestures` addon recommendation

---

guides/release/components/helper-functions.md
guides/v4.6.0/components/helper-functions.md
guides/v4.7.0/components/helper-functions.md
guides/v4.8.0/components/helper-functions.md

@SkoebaSteve updated the helpers content for v4.5 to cover how to use local helpers in https://github.com/ember-learn/guides-source/pull/1888. This PR copies those changes into more recent guides versions as well. The prose/changes were previously reviewed - this is copy-paste.
@SkoebaSteve if there's ever any other changes you want to make to the guides that do not need to go on older versions, you can make your changes in the `release` folder. I think the helper functions made sense to include on older versions as well, though!

Add helper function changes to other guides versions

---

guides/release/in-depth-topics/autotracking-in-depth.md

Changes the "Caching of tracked properties" section of the Autotracking In-Depth guides page to use the `@cached` decorator instead of the lower-level caching primitives APIs.

Update autotracking in-depth guides to use @cached decorator (#1886)

---

.local.dic
guides/release/code-editors/index.md
guides/release/contributing/repositories.md
guides/release/ember-inspector/data.md
guides/release/ember-inspector/object-inspector.md
guides/release/getting-started/anatomy-of-an-ember-app.md
guides/release/getting-started/index.md
guides/release/in-depth-topics/making-api-requests.md
guides/release/in-depth-topics/native-classes-in-depth.md
guides/release/index.md
guides/release/models/creating-updating-and-deleting-records.md
guides/release/models/customizing-adapters.md
guides/release/models/customizing-serializers.md
guides/release/models/defining-models.md
guides/release/models/finding-records.md
guides/release/models/handling-metadata.md
guides/release/models/index.md
guides/release/models/pushing-records-into-the-store.md
guides/release/models/relationships.md
guides/release/pages.yml
guides/release/routing/defining-your-routes.md
guides/release/routing/loading-and-error-substates.md
guides/release/routing/query-params.md
guides/release/routing/specifying-a-routes-model.md
guides/release/services/index.md
guides/release/testing/testing-models.md
guides/release/upgrading/current-edition/native-classes.md
guides/release/upgrading/current-edition/tracked-properties.md

The library's name is standardizing on EmberData with no spaces. Let's get this set across the board where we can.
- This PR is a find-replace for only the `release` directory.
- It does not change the tutorial. That needs to be done in another repo. Sister PR: https://github.com/ember-learn/super-rentals-tutorial/pull/221
- It looks like 2 headings will change. We try not to change these over time, but I think this fits the criteria. Branding is important.

Find/replace Ember Data for EmberData

---

guides/v4.0.0/models/index.md
guides/v4.1.0/models/index.md

Let's backport the fix from #1802 to v4.0.0 and v4.1.0 of the guides. This change fixes a callout regarding the implicit injection for the store service which no longer occurs as of v4.0.0.
This fixes #1803.

guides/models/index: backport #1802

---

guides/release/models/customizing-adapters.md
guides/release/models/customizing-serializers.md

Replace it with plain old regex `replace`.
`replaceAll` would be easier to read, but may not be available in people's projects or node environments.
Similarly I decided not to escape the _ or -, since it's all by itself, but I could add an escape if preferred.
This addresses a blocker for https://github.com/emberjs/rfcs/pull/898

Remove use of @ember/string

---

guides/release/models/finding-records.md
guides/release/models/relationships.md
guides/release/routing/redirection.md

Partially addresses #1921
firstObject is removed in 5.0.

Remove deprecated Ember Data usage of firstObject

---

guides/release/routing/specifying-a-routes-model.md

[RFC-774](https://github.com/emberjs/rfcs/pull/774)
I believe it is safe to merge this now even before the deprecation has been merged, but I'm open to alternative ways to handle this.
https://github.com/emberjs/ember.js/pull/20376

[RFC-774] Remove documentation for implicit route model

---

guides/release/routing/query-params.md
guides/v1.10.0/testing/test-runners.md
guides/v3.15.0/routing/query-params.md
guides/v3.16.0/routing/query-params.md
guides/v3.17.0/routing/query-params.md
guides/v3.18.0/routing/query-params.md
guides/v3.19.0/routing/query-params.md
guides/v3.20.0/routing/query-params.md
guides/v3.21.0/routing/query-params.md
guides/v3.22.0/routing/query-params.md
guides/v3.23.0/routing/query-params.md
guides/v3.24.0/routing/query-params.md
guides/v3.25.0/routing/query-params.md
guides/v3.26.0/routing/query-params.md
guides/v3.27.0/routing/query-params.md
guides/v3.28.0/routing/query-params.md
guides/v4.0.0/routing/query-params.md
guides/v4.1.0/routing/query-params.md
guides/v4.10.0/routing/query-params.md
guides/v4.11.0/routing/query-params.md
guides/v4.12.0/routing/query-params.md
guides/v4.2.0/routing/query-params.md
guides/v4.3.0/routing/query-params.md
guides/v4.4.0/routing/query-params.md
guides/v4.5.0/routing/query-params.md
guides/v4.6.0/routing/query-params.md
guides/v4.7.0/routing/query-params.md
guides/v4.8.0/routing/query-params.md
guides/v4.9.0/routing/query-params.md

@locks brought the issue below to our attention and this fixes it. I've also checked is this happend in other places but that was not the case, except for one weird `<a>` tag in v1.10, so I removed that one too :)
**After**

Fix `<LinkTo />` in title

---

guides/release/components/helper-functions.md

The diff mentioned that the old initial was the @avatarTitle which confused me for a while.
I changed it to @avatarInitial which I assume is what's intended

Use avatarInitial instead of avatarTitle in diff

---

guides/release/components/template-lifecycle-dom-and-modifiers.md
guides/release/upgrading/current-edition/glimmer-components.md

At https://github.com/emberjs/rfcs/pull/934 we're tracking an effort to implement the RFC https://github.com/emberjs/rfcs/pull/811. In that RFC (at
https://github.com/emberjs/rfcs/blob/master/text/0811-element-modifiers.md#how-we-teach-this) there are two things which are suggested for documentation in the guides:
* Update references that mention `ember-modifier` must be installed, since it ships in the default blueprint (confirmed at https://github.com/ember-cli/ember-new-output/blob/master/package.json#L50)
* Introduce the class-based modifier API. In this PR I've linked to the upstream documentation at https://github.com/ember-modifier/ember-modifier#usage to execute on that suggestion. I don't believe we need to laborously explain the class-based APIs to guides readers, it just …

Update the guides for element modifiers

---

guides/release/testing/index.md
guides/release/testing/testing-tools.md

This is part of the RFC-853 work https://github.com/emberjs/rfcs/pull/960
We shouldn't have any mention of ember-mocha or ember-cli-mocha, an if we're not referencing them any more then we don't need to mention how to filter things in Mocha (this PR)

remove references to mocha in the guides

---

package-lock.json
package.json

ember-test-selectors@5 was triggering the following deprecations:
- ember-global
- ember.component.reopen
- template-compiler.registerPlugin

⬆️ Dep on ember-test-selectors@6

---

guides/release/accessibility/components.md

Adding unique-id to the guides is a blocker for finally making it Recommended: https://github.com/emberjs/rfcs/pull/865

Demonstrating unique-id helper

---

package-lock.json
package.json

Extracting parts of the [Shikiji prototype](https://github.com/ember-learn/guides-source/pull/1991) in reviewable bits.
This PR upgrades FastBoot and Prember to the latest versions.
- Prember v2 fixes reading the Fastboot config

deps: Upgrade fastboot and prember

---

guides/release/in-depth-topics/autotracking-in-depth.md

The example for `@cached` was using code that wasn't in the example. Seems like it was missed when the conversion from caching primitives to `@cached` happened in https://github.com/ember-learn/guides-source/pull/1887/files

Correct @cached example

---

scripts/create-new-minor-version
scripts/update-version-links

- prompt user to enter EmberData current version and pass it to update links script
- also handle different ember data version when updating links

fix: allow EmberData version to be set on release:minor script

---

guides/release/components/index.md
guides/release/contributing/index.md
guides/release/contributing/repositories.md

As part of https://github.com/ember-learn/guidemaker-ember-template/issues/179 I took a look at our current header levels used. It turns out we have a few H1s inside of the guide contents. In general there should only be one h1 on a page, which here is the page title, so having H1s inside the content is odd.
This PR replaces the usages (found via regex search) with H2s.

chore: normalize h1 headers in content to h2

---

guides/release/testing/testing-components.md

This is for demonstration purposes. Refer to the discussion at:
https://discuss.emberjs.com/t/the-value-and-benefit-of-assert-expect/20145

testing: Improve examples by avoiding `assert.expect()`

---

guides/release/components/block-content.md

Aaah, I just saw #1894, I hope it's still ok! Some people requested more documentation about named blocks, so here's another proposition 😃

Update block-content.md [Named blocks]

---

guides/release/typescript/core-concepts/ember-data.md
guides/release/typescript/getting-started.md

Adds references to EmberData's alpha native types, which unlock the ability to use Ember native types. Also includes links to the WIP documentation for the EmberData native types.
This helps us move toward recommending emberjs/rfcs#0724 ("Official TypeScript Support") re: https://github.com/emberjs/rfcs/pull/952#issuecomment-2168532426.

Add references to EmberData alpha types

---

app/styles/app.css

Small tweak to make the inline code backticks more readable and easier to scan on the page.
| Before | After |
|--------|--------|
| ![before](https://github.com/ember-learn/guides-source/assets/10243652/929f3c4d-130f-4ac6-bf54-8a8c69b716c8) | ![after](https://github.com/ember-learn/guides-source/assets/10243652/118795c1-d659-4f80-a665-a29b3fea8485) | 
PR to include in styleguide: https://github.com/ember-learn/ember-styleguide/pull/511

style: lighten up backtick code

---

app/styles/app.css
package-lock.json

Upgrades to the latest `ember-styleguide` patch, and removes the temporarily CSS override which now comes from the package.

deps: upgrade ember-styleguide to latest patch

---

guides/release/getting-started/index.md

This link was bragging about nasa.gov being an ember app, but that is no longer true.
If someone wants to maintain some other link or links that's fine but I think it's better to drop this now than worry about that.

Remove outdated link

---

package-lock.json

Upgrades `ember-showdown-shiki` to include AA compliant color changes.
https://github.com/IgnaceMaes/ember-showdown-shiki/releases/tag/ember-showdown-shiki%401.2.0

deps: upgrade `ember-showdown-shiki`

---

package-lock.json

Fixes highlighting empty line diffs.

deps: bump ember-showdown-shiki

---

guides/release/models/relationships.md

New Ember provides `EXTEND_PROTOTYPES: false`, then method like `removeObject` doesn't exist which can be confusing for new developers. Feel free to suggest how write it more pretty 🙏

Replace not existing `removeObject` method

---

guides/release/models/relationships.md

We detected a typo in [this section](https://guides.emberjs.com/release/models/relationships/#toc_removing-relationships).

Fix typo "blockPost" => "blogPost" in code example, section EmberData > Relationships > removing-relationships

---

guides/release/configuring-ember/handling-deprecations.md

As part of discussing https://github.com/emberjs/rfcs/pull/1009, I took another look at the deprecation workflows page. I don't think we need to recommend installing the pre 2.1 deprecation workflow polyfill any more ... 😉 
Not least because it's archived and likely won't even working in the last few versions of Ember: https://github.com/ember-polyfills/ember-debug-handlers-polyfill

Remove discussion of old debug handler polyfill, it's been a minute

---

guides/release/ember-inspector/deprecations.md

As far as I can tell, even the original commit that introduced this `<img>` never contained the corresponding file.

Remove broken image link

---

package.json
pnpm-lock.yaml

https://github.com/ember-learn/guides-source/pull/2071 broke syntax highlighting because guides-sources fails to satisfy ember-shiki's peerDependency on showdown.
By not providing it, we left pnpm free to pick whatever copy it wanted, and thus there was no way to guarantee that ember-shiki and the rest of guides-source were using *the same* copy.

Fix syntax highlighting

---

guides/release/configuring-ember/feature-flags.md

- change `master` branch references to `main`
- fix some grammar issues
- up feature flag example; closes #453

Update feature flags doc

---

guides/release/getting-started/quick-start.md

make it easier to see that configuration is required.
I missed this paragraph even when I was directly looking for it.

add heading about configuring netlify URL handlers

---

guides/release/tutorial/part-1/component-basics.md

Fixed juxtaposed `</div>` and `</Jumbo>` in example handlebars code.
Credit to @bartelsjoshuac

Update component-basics.md to fix juxtaposed lines

---

guides/release/code-editors/index.md

[Ember.js Extension Pack](https://marketplace.visualstudio.com/items?itemName=EmberTooling.emberjs) now lists [Ember Language Server](https://marketplace.visualstudio.com/items?itemName=EmberTooling.vscode-ember) as their used LSP.
Stable Ember Language Server is no longer supported and their [Github page](https://github.com/lifeart/ember-language-server?tab=readme-ov-file) says it was merged into [ember-tooling/ember-language-server](https://github.com/ember-tooling/ember-language-server).

Change LSP to match Ember.js Extension Pack

---

guides/release/testing/testing-tools.md
guides/v4.10.0/testing/testing-tools.md
guides/v4.11.0/testing/testing-tools.md
guides/v4.12.0/testing/testing-tools.md
guides/v4.4.0/testing/testing-tools.md
guides/v4.5.0/testing/testing-tools.md
guides/v4.6.0/testing/testing-tools.md
guides/v4.7.0/testing/testing-tools.md
guides/v4.8.0/testing/testing-tools.md
guides/v4.9.0/testing/testing-tools.md
guides/v5.0.0/testing/testing-tools.md
guides/v5.1.0/testing/testing-tools.md
guides/v5.10.0/testing/testing-tools.md
guides/v5.11.0/testing/testing-tools.md
guides/v5.12.0/testing/testing-tools.md
guides/v5.2.0/testing/testing-tools.md
guides/v5.3.0/testing/testing-tools.md
guides/v5.4.0/testing/testing-tools.md
guides/v5.5.0/testing/testing-tools.md
guides/v5.6.0/testing/testing-tools.md
guides/v5.7.0/testing/testing-tools.md
guides/v5.8.0/testing/testing-tools.md
guides/v5.9.0/testing/testing-tools.md
guides/v6.0.0/testing/testing-tools.md
guides/v6.1.0/testing/testing-tools.md

In https://guides.emberjs.com/release/testing/testing-tools/, there's a link "type of test that you should write" which is broken. This PR fixes the link path.
It seems to have been broken since this link was moved from `index.md` to its own `testing-tools.md` page (e.g. see [4.3](https://guides.emberjs.com/v4.3.0/testing/) the link was in the introduction page, and see [4.4](https://guides.emberjs.com/v4.4.0/testing/testing-tools/) where the link was first moved to a separate page).
See [Deploy Preview](https://deploy-preview-2101--ember-guides.netlify.app/release/testing/testing-tools/) to check that the link is no longer broken.

fix: fix link to test-types.md

---

guides/release/getting-started/quick-start.md

This removes the feature flags around the GJS docs for quickstart 👍 
Edit: this is now ready for review 🎉 myself and @locks went through the updated version on the upcoming 6.5.0 beta and all the generators worked as expected and the output was correct

convert quick start to gjs

---

guides/release/typescript/additional-resources/gotchas.md

For legacy reasons, the docs previously suggested `unknown` as the type for `owner` in component constructors, but we now have an `Owner` type which is the expected type for Glimmer components.

Use explicit Owner type in constructor example

---

guides/release/routing/linking-between-routes.md

- It's explained in the [API documentation here](https://api.emberjs.com/ember/3.2/classes/Ember.Templates.helpers/methods/link-to?anchor=link-to)
- But the guides do not mention it

Explain @activeClass argument

---

guides/release/code-editors/index.md

Atom was discontinued a while ago and the CodeLobster website is dead, so we have a dead link.
Sorry @mansona :P

Remove Atom add CodeLobster IDE from code editors page
